export type CityGuide = {
  intro: string
  scene: string
  where: string
  seasons: string
  tips: string[]
  venues: string[]
  hoods: string[]
}

export const GUIDE_CITIES = [
  { slug: 'new-york',      code: 'NYC', name: 'New York',       state: 'NY' },
  { slug: 'los-angeles',   code: 'LA',  name: 'Los Angeles',    state: 'CA' },
  { slug: 'chicago',       code: 'CHI', name: 'Chicago',        state: 'IL' },
  { slug: 'san-francisco', code: 'SF',  name: 'San Francisco',  state: 'CA' },
  { slug: 'austin',        code: 'AUS', name: 'Austin',         state: 'TX' },
  { slug: 'seattle',       code: 'SEA', name: 'Seattle',        state: 'WA' },
  { slug: 'washington',    code: 'DC',  name: 'Washington',     state: 'DC' },
  { slug: 'boston',        code: 'BOS', name: 'Boston',         state: 'MA' },
  { slug: 'denver',        code: 'DEN', name: 'Denver',         state: 'CO' },
  { slug: 'atlanta',       code: 'ATL', name: 'Atlanta',        state: 'GA' },
  { slug: 'nashville',     code: 'NSH', name: 'Nashville',      state: 'TN' },
  { slug: 'portland',      code: 'PDX', name: 'Portland',       state: 'OR' },
  { slug: 'miami',         code: 'MIA', name: 'Miami',          state: 'FL' },
  { slug: 'philadelphia',  code: 'PHI', name: 'Philadelphia',   state: 'PA' },
  { slug: 'dallas',        code: 'DAL', name: 'Dallas',         state: 'TX' },
  { slug: 'houston',       code: 'HOU', name: 'Houston',        state: 'TX' },
  { slug: 'minneapolis',   code: 'MIN', name: 'Minneapolis',    state: 'MN' },
  { slug: 'san-diego',     code: 'SD',  name: 'San Diego',      state: 'CA' },
  { slug: 'phoenix',       code: 'PHX', name: 'Phoenix',        state: 'AZ' },
  { slug: 'st-louis',      code: 'STL', name: 'St. Louis',      state: 'MO' },
  { slug: 'baltimore',     code: 'BAL', name: 'Baltimore',      state: 'MD' },
  { slug: 'pittsburgh',    code: 'PIT', name: 'Pittsburgh',     state: 'PA' },
  { slug: 'charlotte',     code: 'CHA', name: 'Charlotte',      state: 'NC' },
  { slug: 'raleigh',       code: 'RDU', name: 'Raleigh',        state: 'NC' },
  { slug: 'new-orleans',   code: 'NOLA', name: 'New Orleans',   state: 'LA' },
] as const

export const cityGuides: Record<string, CityGuide> = {
  'new-york': {
    intro: 'New York City offers more free live music per square mile than almost anywhere on earth. From jazz in Central Park to indie rock in Brooklyn, the city\'s music scene operates at full volume year-round — and a surprising amount of it costs nothing to attend.',
    scene: 'NYC\'s free music ecosystem is staggering in its breadth. Lincoln Center Out of Doors fills the plaza every summer with world-class performers. SummerStage brings hundreds of free concerts to Central Park and parks across all five boroughs. The subway itself hosts hundreds of licensed musicians through the MTA\'s Music Under New York program. Jazz at the Village Vanguard occasionally hosts free sets, and dozens of bars in the East Village, Lower East Side, and Williamsburg feature nightly live music with no cover.',
    where: 'Washington Square Park is the city\'s unofficial outdoor living room, with buskers and impromptu jam sessions nearly every warm afternoon. Central Park\'s SummerStage hosts major acts from June through September. Brooklyn\'s Prospect Park Bandshell runs the Celebrate Brooklyn! festival each summer with free headliners. The Seaport District hosts free outdoor concerts along the waterfront. Bryant Park offers lunchtime performances and evening movie screenings with live music preambles.',
    seasons: 'Summer (June–September) is peak free music season in NYC, with SummerStage, Celebrate Brooklyn!, Lincoln Center Out of Doors, and dozens of neighborhood festivals all running concurrently. Spring and fall bring bar and club shows with no cover. Winter concentrates the action indoors — dive bars in the East Village and Bushwick often have free shows nightly.',
    tips: [
      'Check the SummerStage calendar at summerstage.org early — popular shows fill up even when free.',
      'The MTA\'s Music Under New York program features talented buskers at major subway stations; Grand Central and Union Square are especially good.',
      'Many Lower East Side and East Village bars have free music Thursday through Saturday — arrive early for a good spot.',
      'Lincoln Center\'s free programming extends beyond summer; check their calendar for free events year-round.',
      'Follow local music blogs like BrooklynVegan and Pigeons & Planes for up-to-date free show listings.',
    ],
    venues: [
      'Washington Square Park — daily busking and impromptu jams',
      'SummerStage at Central Park — major acts, June–September',
      'Prospect Park Bandshell — Celebrate Brooklyn! festival',
      'Lincoln Center Plaza — Out of Doors summer series',
      'Seaport District — waterfront concert series',
      'Bryant Park — lunchtime and evening performances',
      'Rockefeller Center — seasonal outdoor concerts',
      'McCarren Park — outdoor shows in Williamsburg',
    ],
    hoods: ['Greenwich Village', 'Lower East Side', 'Williamsburg', 'Bushwick', 'Harlem', 'Astoria'],
  },

  'los-angeles': {
    intro: 'Los Angeles may be known for its industry ties, but the city\'s free live music scene runs deep and wide — from beachside stages in Santa Monica to backyard shows in Echo Park, there\'s always something playing that won\'t cost you a dollar.',
    scene: 'LA\'s sprawling geography means free music is scattered across dozens of distinct neighborhoods, each with its own flavor. Grand Performances presents free world music and jazz in the heart of downtown at California Plaza. The city\'s many farmers markets — Melrose, Larchmont, Silver Lake — regularly feature live acts. The Getty Center and Getty Villa both offer free Friday evening concerts. Beach communities from Santa Monica to Long Beach host free outdoor series throughout summer.',
    where: 'The Santa Monica Pier hosts free concerts on Thursday evenings in summer as part of the Twilight Concert Series, drawing big crowds to the beach. Grand Performances at California Plaza in DTLA features free world-class performers on Friday and Saturday nights from May through October. Levitt Pavilion Los Angeles in MacArthur Park offers 50 free concerts each summer. The Hammer Museum in Westwood runs free public programs including music. Silver Lake and Echo Park bars frequently feature local bands with no cover.',
    seasons: 'Year-round sunshine means free outdoor music in LA runs longer than anywhere in the country. The main summer series (Grand Performances, Twilight Concerts, Levitt Pavilion) run May through October. Farmers market music happens weekly all year. Indoor bar shows with no cover are plentiful every night of the week in Silver Lake, Los Feliz, and Highland Park.',
    tips: [
      'The Twilight Concert Series at Santa Monica Pier books surprisingly big names — check the lineup in May before the season starts.',
      'Grand Performances is in a plaza, so bring a blanket and arrive early to stake out a spot.',
      'Many Echo Park and Silver Lake venues have free music on weeknights — check Do LA and Residentadvisor for listings.',
      'The Getty\'s Friday evening programs are free (parking has a fee; take the bus to avoid it).',
      'Griffith Park hosts occasional free concerts and events — check LA Parks and Recreation.',
    ],
    venues: [
      'Santa Monica Pier — Twilight Concert Series, summer Thursdays',
      'California Plaza / Grand Performances — DTLA, May–October',
      'Levitt Pavilion Los Angeles — MacArthur Park, 50 free shows per summer',
      'The Hammer Museum — free public programs, Westwood',
      'The Getty Center — free Friday evening concerts',
      'Silver Lake Lounge — local bands, frequent free shows',
      'The Echo — free or cheap shows in Echo Park',
    ],
    hoods: ['Silver Lake', 'Echo Park', 'Highland Park', 'Downtown LA', 'Santa Monica', 'Venice'],
  },

  'chicago': {
    intro: 'Chicago\'s free music scene is extraordinary, shaped by a deep blues and jazz heritage and a city government that invests heavily in public programming. From the massive Grant Park Music Festival to neighborhood block parties, free live music in Chicago is a year-round institution.',
    scene: 'The Grant Park Music Festival is one of America\'s oldest and most respected free classical music series, running every summer at the Jay Pritzker Pavilion in Millennium Park with world-class orchestral performances. Chicago\'s jazz and blues legacy means dozens of bars and venues book live music with no cover. The Chicago Department of Cultural Affairs runs dozens of free concert series. Blues clubs on the North Side often have no-cover early sets, and house music — invented in Chicago — pulses from bars across the South Side.',
    where: 'Millennium Park\'s Jay Pritzker Pavilion hosts the Grant Park Music Festival on Wednesday and Friday evenings and Saturday afternoons throughout the summer, plus additional free concerts. The Chicago Riverwalk features live music on weekends. Navy Pier hosts free outdoor performances. The Chicago Blues Festival in Grant Park is the world\'s largest free blues festival, held each June. The Chicago Jazz Festival takes over Millennium Park in late August for free.',
    seasons: 'Summer is Chicago\'s peak free music season, running from Memorial Day through Labor Day. The major free festivals — Blues, Jazz, Gospel, World Music — fill the calendar from June through September. The Chicago Architecture Biennial and other fall events include free music programming. Winter drives things indoors; Logan Square and Pilsen bars have frequent free shows.',
    tips: [
      'The Grant Park Music Festival is free and has reserved seating — arrive 30 minutes early for the best spots on the Great Lawn.',
      'The Chicago Blues Festival in June is massive and completely free; arrive midday to avoid the biggest crowds.',
      'Kingston Mines and Buddy Guy\'s Legends occasionally have reduced or free cover on early sets.',
      'The Chicago Department of Cultural Affairs publishes a free events calendar at chicago.gov/city/en/depts/dca.html.',
      'Pilsen and Logan Square have thriving bar music scenes with frequent no-cover nights.',
    ],
    venues: [
      'Jay Pritzker Pavilion, Millennium Park — Grant Park Music Festival',
      'Grant Park — Chicago Blues Festival (June), Chicago Jazz Festival (August)',
      'Chicago Riverwalk — weekend live music',
      'Navy Pier — outdoor summer concerts',
      'Logan Square Auditorium — occasional free events',
      'Empty Bottle — free early shows on some nights',
    ],
    hoods: ['Wicker Park', 'Logan Square', 'Pilsen', 'Andersonville', 'Bronzeville', 'Lincoln Square'],
  },

  'san-francisco': {
    intro: 'San Francisco punches well above its weight for free live music, with a long countercultural tradition that keeps shows accessible. Dolores Park on a sunny afternoon, the Fillmore on a lucky night, and the city\'s many free festivals make SF a genuinely rewarding city for music lovers on a budget.',
    scene: 'SF\'s free music scene is woven into its parks, plazas, and neighborhood bars. Dolores Park in the Mission is the city\'s unofficial outdoor stage, with buskers, amplified sets, and impromptu performances most weekends. Stern Grove Festival is a beloved San Francisco institution — a free summer concert series in a gorgeous eucalyptus grove that has drawn major headliners since 1938. Outside Lands in Golden Gate Park occasionally has free satellite events. The Haight\'s bars and the Mission\'s venues regularly book local acts with no cover.',
    where: 'Stern Grove Festival runs on Sundays from June through August at Sigmund Stern Grove, featuring pop, world music, classical, and jazz headliners — completely free. Yerba Buena Gardens Festival presents free outdoor concerts from May through October in the heart of SoMa. Union Square hosts free performances throughout the year. The Ferry Building often features live music during its Saturday farmers market. Amoeba Music on Haight Street hosts free in-store performances regularly.',
    seasons: 'San Francisco\'s mild climate supports outdoor music nearly year-round, but summer fog can make evening shows chilly — bring a layer. Stern Grove runs June–August; Yerba Buena Gardens Festival runs May–October. Bar shows with no cover happen every night of the week in the Mission, Haight, and SoMa. The weather is often better in September and October than July and August.',
    tips: [
      'Stern Grove is enormously popular — arrive 90 minutes before showtime to get a decent spot on the lawn.',
      'The Yerba Buena Gardens Festival calendar is published at ybgfestival.org and features impressive lineups.',
      'Amoeba Music\'s free in-store shows are intimate and often feature touring acts — check their calendar.',
      'Mission bars like El Rio have frequent free shows, especially on weekend afternoons.',
      'Golden Gate Park has occasional permitted shows and events — check SF Recreation and Parks.',
    ],
    venues: [
      'Sigmund Stern Grove — Stern Grove Festival, Sundays June–August',
      'Yerba Buena Gardens — free concerts May–October',
      'Dolores Park — informal performances and buskers',
      'Union Square — seasonal free programming',
      'Ferry Building — Saturday farmers market music',
      'Amoeba Music, Haight — free in-store performances',
    ],
    hoods: ['The Mission', 'Haight-Ashbury', 'SoMa', 'Castro', 'North Beach', 'Richmond'],
  },

  'austin': {
    intro: 'Austin bills itself as the Live Music Capital of the World, and free live music is absolutely central to that identity. With hundreds of venues booking nightly shows, free outdoor concerts on 6th Street and beyond, and festivals that fill the calendar year-round, Austin may be the best city in America for finding no-cover live music on any given night.',
    scene: 'Austin\'s live music scene is extraordinary in its density and accessibility. Sixth Street is the most famous live music corridor, with indoor and outdoor stages at nearly every venue — many free. Red River Cultural District is where Austin\'s serious music fans go, with clubs like Mohawk, Stubb\'s Outdoor Amphitheater (free outdoor stage), and venues booking rock, punk, and indie with frequent no-cover nights. The Continental Club on South Congress has live music daily. Rainey Street venues book local and touring acts. The parks and public spaces fill with permitted performances regularly.',
    where: 'Stubb\'s Outdoor Amphitheater has a free outdoor stage that books acts on weekend afternoons and evenings. The Continental Club on South Congress has live music every day, often free during happy hour and early sets. Waterloo Park hosts Austin\'s free concert series. The Long Center has free "ACL Live at the Long Center" events. Red River Cultural District venues — Empire Control Room, Mohawk, Parish — have frequent free shows. South Congress Ave bars book local acts with no cover many nights.',
    seasons: 'Austin is a year-round music city, but spring (March–May) and fall (September–November) are peak free music seasons with perfect weather. South by Southwest in March transforms the entire city into one giant free music event — unofficial showcases everywhere. Austin City Limits Music Festival in October has a free view from Barton Springs nearby. Summer is hot but shows continue indoors and in the cooler evenings.',
    tips: [
      'During SXSW (March), dozens of free outdoor showcases happen across the city — follow local Austin music blogs for the unofficial show lists.',
      'Stubb\'s free outdoor stage books real acts and is all-ages — worth checking their calendar regularly.',
      'The Continental Club has music daily; the Sunday brunch show is a beloved Austin tradition.',
      'Red River Cultural District venues post their calendars on Austin\'s Do512 site for easy browsing.',
      'Many venues on 6th Street have no cover before 10pm — go early for free music, stay if you like the act.',
    ],
    venues: [
      'Stubb\'s Outdoor Amphitheater — free outdoor stage, weekends',
      'The Continental Club — live music daily, South Congress',
      'Mohawk — indoor and outdoor stages, frequent free shows',
      'Empire Control Room — Red River Cultural District',
      'Waterloo Park — city-sponsored free concerts',
      'Long Center — free community programming',
      'Antone\'s — legendary blues and roots venue, occasional free shows',
    ],
    hoods: ['Red River Cultural District', 'South Congress', '6th Street', 'Rainey Street', 'East Austin', 'South Lamar'],
  },

  'seattle': {
    intro: 'Seattle\'s music scene runs far deeper than grunge nostalgia — it\'s a thriving, diverse ecosystem of free outdoor concerts, public park shows, and neighborhood bars where local talent plays nightly without a cover charge. The city\'s parks and waterfront are especially rich territory in the summer months.',
    scene: 'Seattle Center is the heart of the city\'s free public music programming, with the Mural Amphitheater hosting concerts, festivals, and community events. The Seattle Chamber Music Society presents free summer concerts. Benaroya Hall has occasional free lobby concerts. The city\'s bar scene — Capitol Hill, Belltown, Fremont — features nightly live music at venues where the door charge is often zero. The Fremont Sunday Market features live music from buskers and local acts. Seattle\'s folk and Americana scenes are particularly active with affordable and free shows.',
    where: 'Seattle Center\'s Mural Amphitheater hosts free concerts during summer and during events like Folklife Festival (Memorial Day weekend, completely free) and Bumbershoot\'s free park stages. Victor Steinbrueck Park near Pike Place Market features views and occasional busking. Cal Anderson Park in Capitol Hill is a gathering spot with informal music. The Fremont neighborhood hosts its own solstice festival with free music. Jazz Alley occasionally has free early-bird shows.',
    seasons: 'Summer is peak season for Seattle outdoor music (July–September, when rain is least likely). The Northwest Folklife Festival on Memorial Day weekend is one of the largest folk music festivals in the country and completely free. Seattle\'s indoor music scene is vibrant year-round; Capitol Hill\'s bars book acts every night. The shorter days and rain of fall and winter push things indoors but don\'t slow them down.',
    tips: [
      'Northwest Folklife Festival at Memorial Day weekend is a must — five stages, all free, all weekend at Seattle Center.',
      'Capitol Hill\'s bars (Chop Suey, Neumos, Barboza) sometimes have free or cheap early shows — check the venue calendars.',
      'The Fremont neighborhood is particularly good for stumbling onto live music during weekend street fairs and markets.',
      'Seattle\'s music blog The Stranger keeps a comprehensive free events calendar.',
      'Bring a rain layer even in summer — Seattle evenings can be damp.',
    ],
    venues: [
      'Seattle Center Mural Amphitheater — free summer concerts and festivals',
      'Cal Anderson Park — informal music, Capitol Hill',
      'Pike Place Market — buskers and scheduled performers',
      'Fremont Sunday Market — weekly live music',
      'Neumos — Capitol Hill, occasional free early shows',
      'Tractor Tavern — Ballard, roots and folk, occasional no-cover nights',
    ],
    hoods: ['Capitol Hill', 'Fremont', 'Ballard', 'Belltown', 'Georgetown', 'Columbia City'],
  },

  'washington': {
    intro: 'Washington, DC offers an exceptional roster of free live music fueled by the Smithsonian\'s landmark summer programming, the Kennedy Center\'s Millennium Stage, and a thriving neighborhood bar scene across Shaw, U Street, and Adams Morgan.',
    scene: 'The Kennedy Center\'s Millennium Stage presents free one-hour performances every single day at 6pm — 365 days a year. That alone makes DC exceptional. The Smithsonian Folk Life Festival on the National Mall is one of the largest cultural events in the country and completely free. The National Gallery of Art holds free Sunday afternoon chamber music concerts. DC\'s U Street Corridor, long the heart of the city\'s Black musical tradition, remains a live music hub with bars booking jazz, soul, and go-go nightly.',
    where: 'The Kennedy Center Millennium Stage is the most reliable free music venue in America — every day, 6pm, world-class performers, no tickets required. The National Mall hosts concerts during the Smithsonian Folk Life Festival (late June–July 4th) and other national events. Georgetown Waterfront Park has free summer concerts. Wolf Trap National Park for the Performing Arts in nearby Vienna, VA hosts free lawn seating at ticketed shows. U Street venues like Twins Jazz and Blues Alley occasionally have no-cover sets.',
    seasons: 'DC\'s free music calendar peaks in summer with Folk Life Festival, outdoor concerts on the Mall, and neighborhood festivals. The Kennedy Center Millennium Stage is year-round and climate-controlled. U Street, Shaw, and Adams Morgan bars book live acts year-round. Spring cherry blossom season brings additional outdoor programming to the Mall.',
    tips: [
      'The Kennedy Center Millennium Stage is genuinely world-class and always free — bookmark kennedy-center.org/millennium-stage.',
      'Smithsonian Folk Life Festival runs two weeks around the July 4th holiday; arrive early as crowds grow throughout the day.',
      'U Street and Shaw bars have excellent live jazz and go-go on weekend nights — cover charges vary but free nights are common.',
      'The National Gallery of Art\'s Sunday concerts in the East Building Garden Court are free and elegant.',
      'Check DC\'s local blog DCist for free event roundups each week.',
    ],
    venues: [
      'Kennedy Center Millennium Stage — free daily at 6pm, year-round',
      'National Mall — Folk Life Festival, seasonal outdoor concerts',
      'National Gallery of Art — free Sunday afternoon concerts',
      'Georgetown Waterfront Park — summer outdoor series',
      'Yards Park — free concerts at the Navy Yard waterfront',
      'Songbyrd Music House — Adams Morgan, occasional free shows',
    ],
    hoods: ['U Street Corridor', 'Shaw', 'Adams Morgan', 'Georgetown', 'H Street NE', 'Petworth'],
  },

  'boston': {
    intro: 'Boston\'s free music scene stretches from summer waterfront concerts to year-round jazz in historic venues. The city\'s dense university population fuels a lively bar and club scene where no-cover nights are common, and the Hatch Shell on the Esplanade is one of the great free outdoor music venues in New England.',
    scene: 'The Hatch Memorial Shell on the Charles River Esplanade is Boston\'s crown jewel for free outdoor music, hosting the Boston Pops Fireworks Spectacular every July 4th and the summer-long Boston Landmarks Orchestra series. Harvard and MIT bring world-class performers to campus venues open to the public, often free. The Boston Common and Christopher Columbus Park host outdoor concerts. Newbury Street on summer evenings fills with buskers. Allston-Brighton\'s bar scene — fueled by students — features nightly live music with no cover.',
    where: 'The Hatch Shell Esplanade hosts the Boston Landmarks Orchestra free classical concerts on Wednesday evenings in July and August. The City of Boston runs free outdoor concerts at City Hall Plaza and other parks throughout summer. Jamaica Plain\'s outdoor spaces and Brookline\'s Coolidge Corner neighborhood feature street performers and small venues with live music. The Middle East in Cambridge books bands nightly, with some free shows. Charlie\'s Kitchen in Harvard Square often has free or cheap music.',
    seasons: 'Summer (June–September) is peak outdoor music season with Hatch Shell programming, waterfront concerts, and neighborhood festivals. Fall coincides with the academic year restart — the bar and club scene in Allston, Cambridge, and Jamaica Plain is most active September through May. Winter concentrates music in warm bars; Allston has the densest cluster of regular free shows.',
    tips: [
      'Boston Landmarks Orchestra at the Hatch Shell is free and excellent — bring a picnic and arrive an hour early.',
      'Allston\'s bars (Great Scott, O\'Brien\'s, Brighton Music Hall) have frequent free or cheap shows — check Do617 for listings.',
      'Harvard and MIT post public event calendars with many free music performances.',
      'The New England Conservatory hosts free student recitals most evenings during the academic year.',
      'First Friday events in various Boston neighborhoods feature free gallery openings with live music.',
    ],
    venues: [
      'Hatch Memorial Shell, Esplanade — Boston Landmarks Orchestra, summer Wednesdays',
      'City Hall Plaza — outdoor summer concert series',
      'Christopher Columbus Park — waterfront performances',
      'Middle East, Cambridge — frequent free and cheap shows',
      'Great Scott, Allston — local bands, occasional free nights',
      'NEC Jordan Hall — free student recitals',
    ],
    hoods: ['Allston', 'Cambridge', 'Jamaica Plain', 'Somerville', 'South End', 'Fenway'],
  },

  'denver': {
    intro: 'Denver\'s outdoor lifestyle and thriving arts scene translate into exceptional free music options, from Civic Center Park festivals to Red Rocks watching parties. The city\'s breweries and music-forward bars keep the calendar full year-round, even when the mountains call.',
    scene: 'Denver has a passionate music culture that spans bluegrass, indie, hip-hop, and country. The city\'s free outdoor programming centers on Civic Center Park, which hosts dozens of free events annually including the Taste of Colorado (Labor Day, with free stages) and PrideFest. Levitt Pavilion Denver presents 50 free concerts each summer at Ruby Hill Park. Larimer Square and RiNo (River North Art District) bars book local acts nightly, often with no cover. The Colorado Symphony performs free concerts in the park. Red Rocks Amphitheatre, though ticketed, sometimes has free community days.',
    where: 'Levitt Pavilion Denver at Ruby Hill Park runs 50 free concerts from June through September featuring diverse genres from bluegrass to hip-hop. Civic Center Park hosts major free festivals throughout summer. Confluence Park along the South Platte River has outdoor spaces with informal music. The 16th Street Mall features buskers and performers. RiNo\'s bar-heavy stretch along Brighton Boulevard and Larimer Street books local acts with frequent free admission.',
    seasons: 'Denver\'s 300 days of sunshine support outdoor music from April through October. The Levitt Pavilion season (June–September) is particularly strong. Fall brings the Great American Beer Festival with satellite music events. Winter concentrates free shows in RiNo and Capitol Hill bars. Bluegrass is popular year-round, with free jams at various venues.',
    tips: [
      'Levitt Pavilion\'s 50 free concerts at Ruby Hill Park cover an impressive range of genres — check levittdenver.org for the season lineup.',
      'RiNo\'s bar and gallery scene has frequent free music, especially during First Friday art walks.',
      'The 16th Street Mall has scheduled performers; check Denver Arts & Venues for programming.',
      'Brewing companies like Great Divide and Ratio Beerworks host free music events regularly.',
      'Denver\'s bluegrass community hosts free jams at locations posted on Colorado Bluegrass Music Society\'s calendar.',
    ],
    venues: [
      'Ruby Hill Park / Levitt Pavilion Denver — 50 free concerts, summer',
      'Civic Center Park — free festival stages throughout summer',
      'Confluence Park — informal outdoor performances',
      'Larimer Lounge — RiNo, local music, occasional free shows',
      'Globe Hall — Denver\'s music-forward event space, free sometimes',
      'Summit Music Hall — occasional free early shows',
    ],
    hoods: ['RiNo (River North)', 'Capitol Hill', 'Larimer Square', 'Baker', 'Five Points', 'Highlands'],
  },

  'atlanta': {
    intro: 'Atlanta is a music city of enormous energy, home to hip-hop royalty, a booming indie scene, and a gospel tradition that runs through everything. Free live music in Atlanta spans free stages at Piedmont Park to rooftop shows in Old Fourth Ward, with something happening every night of the week.',
    scene: 'Atlanta\'s free music landscape reflects the city\'s musical breadth. Music Midtown at Piedmont Park features free stages alongside ticketed acts. The Atlanta BeltLine\'s Eastside Trail hosts Lantern Parade and summer concert series. The Atlanta Jazz Festival at Piedmont Park in late May is one of the largest free jazz festivals in the Southeast. Little Five Points and East Atlanta Village bars book local indie and punk acts nightly, often free. The city\'s thriving hip-hop and R&B scene surfaces at free day parties and outdoor events throughout the year.',
    where: 'Piedmont Park is Atlanta\'s outdoor music anchor, hosting the Atlanta Jazz Festival (Memorial Day weekend, free) and Dogwood Festival (free stages). The Atlanta BeltLine trail connects neighborhoods and hosts pop-up music events. Old Fourth Ward\'s Ponce City Market plaza hosts free concerts. Krog Street Market has occasional free music. Little Five Points\'s outdoor spaces feature street performers and informal shows. The Tabernacle occasionally has free events, and Terminal West books local acts with affordable covers.',
    seasons: 'Spring (March–May) is ideal for outdoor music in Atlanta, with the Jazz Festival being the highlight. Summer is hot and humid but outdoor shows continue with evening starts. Fall is excellent for outdoor events. Winter is mild enough for outdoor programming and bar shows stay active year-round. The BeltLine trail programming picks up in spring.',
    tips: [
      'Atlanta Jazz Festival at Piedmont Park over Memorial Day weekend is completely free — multiple stages, national headliners.',
      'The Atlanta BeltLine publishes its event calendar at beltline.org — free programming happens along the trail regularly.',
      'East Atlanta Village (EAV) bars like 529 and Flatiron often have free local shows on weeknights.',
      'Ponce City Market hosts free outdoor concerts on its rooftop and plaza; check the events page.',
      'Little Five Points is worth walking through on weekend evenings for street performers and bar music.',
    ],
    venues: [
      'Piedmont Park — Atlanta Jazz Festival, Dogwood Festival, summer concerts',
      'Ponce City Market — free outdoor and rooftop shows',
      'The Atlanta BeltLine Eastside Trail — pop-up performances',
      '529 — East Atlanta Village, local bands, low/no cover',
      'Smith\'s Olde Bar — Midtown, free early shows some nights',
      'Terminal West — Westside, occasional free events',
    ],
    hoods: ['Little Five Points', 'East Atlanta Village', 'Old Fourth Ward', 'Midtown', 'Westside', 'Decatur'],
  },

  'nashville': {
    intro: 'Nashville is the city that defined American country music and remains its beating heart — and an enormous amount of that music is free. Honky-tonks on Lower Broadway blast live bands all day every day at no charge, and the city\'s diverse neighborhood venues keep every genre accessible without a cover.',
    scene: 'Lower Broadway is Nashville\'s most extraordinary free music corridor — a strip of honky-tonks where bands play from noon until 3am, seven days a week, with no cover charge. Venues like Tootsie\'s Orchid Lounge, Robert\'s Western World, and Legends Corner have multiple floors and stages, all free. The Ryman Auditorium occasionally hosts free programming. Nashville\'s East Nashville and 12 South neighborhoods have bar scenes with nightly live music. The city\'s songwriter community means acoustic nights at writers\' rounds are frequent and often free.',
    where: 'Lower Broadway honky-tonks are the crown jewel of free Nashville music — arrive any afternoon and you\'ll find live bands. Robert\'s Western World is legendary for its vintage country sound. Tootsie\'s Orchid Lounge has multiple floors and stages. The Stage on Broadway is another solid option. Outside the tourist zone, Basement East in East Nashville and 3rd and Lindsley book strong local and regional acts with low or no covers. The East Nashville neighborhood\'s bars on Gallatin Pike and Woodland Street feature emerging artists.',
    seasons: 'Nashville\'s free music scene is year-round but peaks in spring and fall with beautiful outdoor weather for the patios. Summer is hot, but Lower Broadway\'s air-conditioned honky-tonks keep the music going. CMA Fest in June floods the city with outdoor free stages on Broadway and the riverfront. Tin Pan South Songwriter Festival in spring features free rounds at various venues.',
    tips: [
      'Lower Broadway honky-tonks are free all the time — tip the bands well, they work for tips.',
      'Robert\'s Western World is the locals\' favorite on Broadway; arrive early for a seat near the stage.',
      'CMA Fest (June) has massive free stages on Broadway and along the Cumberland River — check the schedule.',
      'Tin Pan South (spring) features free songwriter rounds at venues across the city — absolutely worth attending.',
      'East Nashville\'s Woodland Street and Gallatin Pike bars have free music most nights — a better look at Nashville\'s current scene.',
    ],
    venues: [
      'Robert\'s Western World — Lower Broadway, live bands daily, free',
      'Tootsie\'s Orchid Lounge — multiple free stages, all day every day',
      'Legends Corner — classic honky-tonk, free music',
      'The Stage on Broadway — free shows, multiple floors',
      'Basement East — East Nashville, local music, low covers',
      '3rd and Lindsley — local and regional acts, affordable shows',
    ],
    hoods: ['Lower Broadway', 'East Nashville', '12 South', 'Germantown', 'The Gulch', 'Wedgewood-Houston'],
  },

  'portland': {
    intro: 'Portland\'s fiercely independent music culture means free and all-ages shows are a point of pride. From Mississippi Avenue bars to outdoor concerts in Tom McCall Waterfront Park, Portland delivers consistently excellent free music rooted in its DIY ethos.',
    scene: 'Portland\'s free music scene reflects the city\'s commitment to accessibility and indie culture. Mississippi Avenue on the North Portland side has bars that book local acts nightly with no cover. The Portland waterfront hosts free summer concerts during the Rose Festival and other events. McMenamins venues across the city (Kennedy School, Crystal Ballroom, Edgefield) occasionally host free outdoor music. The Aladdin Theater has some free shows. Portland\'s folk and bluegrass community is active, with free jams at Alberta Street bars and community centers.',
    where: 'Tom McCall Waterfront Park along the Willamette River hosts free concerts during the Rose Festival (June) and other summer events. Mississippi Avenue\'s walkable stretch of bars, restaurants, and music venues is the best neighborhood for free live music any night of the week. Alberta Arts District features free outdoor music during Last Thursday art walks. Pioneer Courthouse Square hosts free concerts and events. The Kennedy School\'s courtyard pub features live music in a converted schoolhouse setting.',
    seasons: 'Portland\'s rainy season (October–May) pushes free music indoors to bars on Mississippi, Alberta, and Division Streets. Summer (June–September) brings outdoor concerts to waterfront parks and neighborhood streets. The Last Thursday art walks on Alberta Street in summer are a Portland institution with street music. October\'s Portland Jazz Festival has free outdoor events.',
    tips: [
      'Mississippi Avenue\'s bars (White Eagle Saloon, Mississippi Studios) book great local acts — walk the strip on any weekend evening.',
      'Last Thursday on Alberta Street (last Thursday of each month, summer) features free outdoor performances and art.',
      'McMenamins Kennedy School hosts free outdoor movies with occasional live music preambles — check their calendar.',
      'Portland\'s music blog Portland Mercury has an events section with free show listings.',
      'The Rose Festival (June) includes free stages along the waterfront and in Tom McCall Park.',
    ],
    venues: [
      'Tom McCall Waterfront Park — Rose Festival stages, summer concerts',
      'Mississippi Studios — frequent affordable and free shows',
      'White Eagle Saloon — Mississippi Ave, live music nightly',
      'Alberta Arts District — Last Thursday outdoor music, summer',
      'Pioneer Courthouse Square — free seasonal programming',
      'Kennedy School (McMenamins) — free courtyard events',
    ],
    hoods: ['Mississippi Avenue', 'Alberta Arts District', 'Division Street', 'Pearl District', 'Hawthorne', 'Sellwood'],
  },

  'miami': {
    intro: 'Miami\'s music scene is as vibrant as its nightlife, with an infusion of Latin, Caribbean, and electronic influences making the city\'s free shows uniquely energetic. Wynwood\'s art district, Calle Ocho in Little Havana, and the beaches all contribute to a rich ecosystem of no-cover live music.',
    scene: 'Miami\'s free music landscape reflects the city\'s multicultural character. Wynwood hosts free outdoor concerts during Art Basel and First Fridays, with local and international acts. Little Havana\'s Calle Ocho Festival in March is one of the world\'s largest street festivals, featuring free stages with Latin music across eight blocks. Miami Beach\'s Lincoln Road pedestrian mall features regular buskers and scheduled performers. Bayfront Park hosts free concerts and events throughout the year. The Adrienne Arsht Center for the Performing Arts has free community programming.',
    where: 'Bayfront Park Amphitheater in downtown Miami hosts free and low-cost concerts throughout the year. Lincoln Road Mall in South Beach features regular live music from buskers and scheduled performers, especially on weekends. Wynwood Walls\' surrounding streets come alive during Art Walk (second Saturday monthly) with free music. Calle Ocho in Little Havana has free outdoor stages on Viernes Culturales (Cultural Fridays, last Friday monthly). Coconut Grove\'s streets and plazas feature buskers and free outdoor performances.',
    seasons: 'Miami\'s free music season is truly year-round thanks to the climate. Winter (December–March) is peak tourist season with Art Basel bringing major events and free outdoor programming. Spring\'s Calle Ocho Festival is unmissable. Summer is hot and humid but evening outdoor shows continue, especially on the water. Hurricane season (June–November) doesn\'t typically interrupt the music schedule much.',
    tips: [
      'Calle Ocho Festival in March is one of the best free music events in the country — arrive early and explore the side streets.',
      'Viernes Culturales (Cultural Fridays) on Calle Ocho are free every last Friday of the month with live Latin music.',
      'Art Basel week (early December) floods Wynwood with free outdoor music events — walk the neighborhood.',
      'Lincoln Road Mall is great for free music on weekend evenings — the buskers here are often very talented.',
      'Follow @VisitMiami and Wynwood neighborhood accounts for free event announcements.',
    ],
    venues: [
      'Bayfront Park Amphitheater — free and low-cost concerts, year-round',
      'Lincoln Road Mall — buskers and scheduled performers, weekends',
      'Calle Ocho, Little Havana — Viernes Culturales (last Friday monthly)',
      'Wynwood Walls area — Art Walk (second Saturday monthly)',
      'Coconut Grove — street performers and outdoor spaces',
      'Adrienne Arsht Center — free community programming',
    ],
    hoods: ['Wynwood', 'Little Havana', 'South Beach', 'Coconut Grove', 'Brickell', 'Little Haiti'],
  },

  'philadelphia': {
    intro: 'Philadelphia\'s free music scene draws on the city\'s deep soul, R&B, and indie rock roots. From the Mann Center\'s free lawn to outdoor concerts along the Delaware River waterfront, Philly offers genuinely excellent no-cost music from world-class performers to beloved local acts.',
    scene: 'Philadelphia has a strong tradition of accessible live music anchored by the Mann Center for the Performing Arts in Fairmount Park, which offers free lawn admission to many of its summer concerts. The Kimmel Center hosts free Community Days and public programming. Penn\'s Landing along the Delaware River waterfront presents free outdoor concerts throughout summer. The city\'s WXPN radio station promotes an active indie scene with frequent free shows. Northern Liberties, Fishtown, and South Street bars book local acts nightly.',
    where: 'The Mann Center for the Performing Arts in West Fairmount Park presents ticketed performances with free lawn admission — bring a blanket and you can see major acts for free. Penn\'s Landing hosts the Philadelphia Folk Festival\'s free stages and riverfront concerts. Spruce Street Harbor Park features live music on weekends. The Kimmel Cultural Campus hosts free Community Days. Fishtown\'s bars — Kung Fu Necktie, Ortlieb\'s — book exceptional local and national acts with accessible covers.',
    seasons: 'Summer (June–September) is peak outdoor music season with Mann Center, Penn\'s Landing, and neighborhood block parties. The Philadelphia Folk Festival in late August is one of the best folk festivals in the country, with free outdoor stages. Fall is excellent for bar shows in Fishtown and Northern Liberties. Winter brings free indoor programming at the Kimmel Center.',
    tips: [
      'Mann Center\'s free lawn is one of the best free music experiences in the Mid-Atlantic — arrive an hour early for a good spot.',
      'WXPN (88.5 FM) publishes extensive free concert listings and hosts its own free events throughout the year.',
      'Fishtown\'s Ortlieb\'s is a legendary jazz venue with accessible covers and a great local scene.',
      'Penn\'s Landing hosts free family-friendly concerts on summer weekends — check delawareriverwaterfront.com.',
      'South Street\'s bars have live music nightly; many have no cover before 10pm.',
    ],
    venues: [
      'Mann Center for the Performing Arts — free lawn admission to ticketed shows',
      'Penn\'s Landing / Spruce Street Harbor Park — free waterfront concerts',
      'Kimmel Cultural Campus — free Community Days and public programming',
      'Ortlieb\'s — Fishtown, jazz and roots music, accessible pricing',
      'Kung Fu Necktie — Fishtown, indie and rock, low covers',
      'World Cafe Live — WXPN music venue, frequent free events',
    ],
    hoods: ['Fishtown', 'Northern Liberties', 'South Street', 'East Passyunk', 'Old City', 'West Philadelphia'],
  },

  'dallas': {
    intro: 'Dallas offers a surprisingly rich free music scene anchored by the AT&T Performing Arts Center\'s free programming, Deep Ellum\'s legendary live music district, and a growing roster of outdoor concerts across the city\'s parks and plazas.',
    scene: 'Dallas\'s free music landscape is anchored by Deep Ellum, the city\'s historic live music district where venues book blues, rock, jazz, and hip-hop nightly. The AT&T Performing Arts Center\'s Annette Strauss Artist Square is one of Dallas\'s best free outdoor venues, hosting concerts and cultural events. The City of Dallas runs free outdoor programming at Klyde Warren Park above the Woodall Rodgers Freeway. The Dallas Arts District — one of the largest in the country — contains museums and spaces with free public programming. Granada Theater and Three Links book local acts with frequent no-cover nights.',
    where: 'Klyde Warren Park hosts free concerts, yoga classes, and events nearly every weekend and many weeknights — one of the best urban parks in Texas. AT&T Performing Arts Center\'s outdoor spaces present free events throughout the year. Deep Ellum\'s clubs and bars line Elm Street and Commerce Street with live music nightly; many have no cover before 9 or 10pm. Fair Park — home of the State Fair — hosts free outdoor programming at other times of year. The Perot Museum and Dallas Museum of Art have occasional free music events.',
    seasons: 'Spring (March–May) and fall (September–November) are the best seasons for outdoor free music in Dallas, with temperatures that make extended outdoor time comfortable. Klyde Warren Park is active year-round. Summer brings outdoor shows with evening starts. Deep Ellum\'s indoor venues are active every night regardless of season.',
    tips: [
      'Klyde Warren Park\'s free events calendar is at klydewarrenpark.org — something happens almost every weekend.',
      'Deep Ellum venues often have no cover before 9pm; explore the strip on a Friday or Saturday evening.',
      'The AT&T Performing Arts Center publishes its free outdoor programming at attpac.org.',
      'Three Links in Deep Ellum has excellent free punk and rock shows — check their calendar.',
      'Dallas\' local blog D Magazine Events covers free music listings.',
    ],
    venues: [
      'Klyde Warren Park — free concerts nearly every weekend',
      'Annette Strauss Artist Square, AT&T PAC — free outdoor events',
      'Granada Theater — local and touring acts, occasional free shows',
      'Three Links — Deep Ellum, punk and rock, frequent free nights',
      'The Rustic — free outdoor stage, Uptown',
      'Deep Ellum venues (Elm Street) — live music nightly, often free early',
    ],
    hoods: ['Deep Ellum', 'Uptown', 'Lower Greenville', 'Bishop Arts District', 'Oak Lawn', 'Design District'],
  },

  'houston': {
    intro: 'Houston\'s extraordinary cultural diversity shapes a free music scene that\'s genuinely unlike anywhere else — Tejano, blues, hip-hop, Vietnamese pop, and classical music all coexist in a city where outdoor parks, Discovery Green, and neighborhood venues make live music widely accessible.',
    scene: 'Houston\'s free music landscape is defined by its multicultural character. Discovery Green in downtown Houston is the city\'s premier free music venue, hosting concerts nearly every weekend from diverse genres. The Miller Outdoor Theatre in Hermann Park presents free performances from the Houston Symphony, Shakespeare, opera, and touring musical acts from April through October. The Midtown neighborhood and Montrose\'s bars book local acts nightly. Houston\'s Tejano and conjunto music traditions surface in free outdoor performances at parks and community events on the East Side.',
    where: 'Miller Outdoor Theatre in Hermann Park presents completely free performances — orchestra, Broadway touring shows, international music — from spring through fall. Discovery Green downtown has a dedicated performance stage with free concerts most weekends. Market Square Park in downtown Houston hosts outdoor events with live music. The Menil Collection\'s lawn in Montrose is a beautiful setting for occasional free outdoor performances. East End and Midtown bars book diverse local acts with regular free nights.',
    seasons: 'Spring (March–May) and fall (September–November) are ideal for outdoor free music in Houston, with Miller Outdoor Theatre running at full capacity. Discovery Green hosts events year-round. Summer is brutally hot but Miller continues its season with evening performances. Houston\'s indoor bar scene runs year-round regardless of weather.',
    tips: [
      'Miller Outdoor Theatre\'s season runs roughly April–October with free shows every week — check milleroutdoortheatre.com for the full calendar.',
      'Discovery Green hosts free concerts almost every weekend; check discoverygreen.com for the events calendar.',
      'Montrose\'s bars (Rudyard\'s, Poison Girl) have free local music regularly on weekend nights.',
      'Houston Press covers the local music scene and maintains a free events listing.',
      'The East End and Second Ward have community events with live Tejano and Latin music that are often free.',
    ],
    venues: [
      'Miller Outdoor Theatre, Hermann Park — free shows, spring through fall',
      'Discovery Green — free concerts most weekends, year-round',
      'Market Square Park — downtown, occasional free events',
      'Rudyard\'s British Pub — Montrose, local bands, frequent free shows',
      'The Menil Collection — occasional free outdoor performances',
      'MATCH (Midtown Arts and Theater Center) — community programming',
    ],
    hoods: ['Montrose', 'Midtown', 'East End', 'Heights', 'Museum District', 'Washington Avenue'],
  },

  'minneapolis': {
    intro: 'Minneapolis punches well above its weight in music — a city that launched Prince, the Replacements, and Hüsker Dü has an enduring commitment to live music. Free outdoor concerts, Nicollet Mall performers, and a thriving bar scene in Northeast and Uptown keep the calendar packed.',
    scene: 'Minneapolis\'s free music scene is shaped by its passionate local music culture and a city government that invests in public programming. The Minneapolis Park and Recreation Board hosts dozens of free concerts across the city\'s park system. Nicollet Mall in downtown Minneapolis features free busking and scheduled performers. The Loring Park area hosts outdoor events with live music. Surly Brewing and other local breweries book live acts regularly, often free. Northeast Minneapolis\'s arts district bar scene features nightly live music with accessible prices.',
    where: 'Loring Park hosts free outdoor concerts during summer, including the Pride festival\'s free stages. Minneapolis Park Board\'s Summer Music programs bring concerts to neighborhood parks across the city from June through August. The Sculpture Garden adjacent to Walker Art Center occasionally has free programming. First Avenue\'s outdoor stage and 7th Street Entry book local acts with frequent no-cover shows. The Minneapolis Farmer\'s Market features live music on weekends.',
    seasons: 'Minneapolis winter is brutal, which makes the city\'s summer outdoor programming especially cherished. Free outdoor concerts run from June through August. The bar scene in Northeast, Uptown, and Lyndale is year-round and active. Summer music festivals at Loring Park and in neighborhood parks make warm-weather weekends exceptional for free music.',
    tips: [
      'Minneapolis Park Board publishes its summer concert calendar at minneapolisparks.org — free concerts happen in parks across all neighborhoods.',
      'First Avenue\'s outdoor area and 7th Street Entry have more affordable and free shows than you\'d expect given the venue\'s legendary status.',
      'Northeast Minneapolis (NEMA) has an active arts and bar scene with free music at venues like Dusty\'s and other neighborhood spots.',
      'Surly Brewing\'s biergarten and events space hosts free concerts regularly.',
      'City Pages (and its successor outlets) cover Minneapolis free music listings.',
    ],
    venues: [
      'Loring Park — free outdoor concerts, summer',
      'Minneapolis Park System — neighborhood parks, summer concert series',
      '7th Street Entry — local bands, frequent free nights',
      'Surly Brewing Destination Brewery — free outdoor concerts',
      'Nicollet Mall — buskers and scheduled performers',
      'Walker Art Center / Sculpture Garden — free occasional programming',
    ],
    hoods: ['Northeast Minneapolis', 'Uptown', 'Lyndale', 'North Loop', 'Seward', 'Longfellow'],
  },

  'san-diego': {
    intro: 'San Diego\'s perfect weather and beach culture make free outdoor music a year-round reality. From Balboa Park\'s historic free organ pavilion to Gaslamp Quarter bars and beach community concerts, the city delivers accessible live music against a spectacular backdrop.',
    scene: 'San Diego\'s free music scene benefits enormously from its Mediterranean climate — outdoor shows are possible almost every day of the year. Balboa Park\'s Spreckels Organ Pavilion hosts free Sunday afternoon organ concerts year-round, one of the longest-running free concert series in the world. The Del Mar Racetrack\'s Twilight in the Park series brings big names for free. The Gaslamp Quarter\'s bars book live music nightly. Pacific Beach, Ocean Beach, and North Park neighborhoods each have bar scenes with frequent free shows.',
    where: 'Spreckels Organ Pavilion in Balboa Park holds free public concerts every Sunday at 2pm — a century-old tradition. Embarcadero Marina Park hosts free outdoor concerts. The Del Mar Fairgrounds hosts free music during the fair and occasional off-season events. North Park\'s 30th Street corridor is the city\'s most active neighborhood music scene, with bars booking local acts nightly. Ocean Beach\'s Newport Avenue has free outdoor events during the OB Street Fair and year-round.',
    seasons: 'San Diego is genuinely year-round for outdoor free music. The Balboa Park organ concerts happen every Sunday. Summer brings beach concerts, Del Mar events, and waterfront programming. Fall and spring are perfect outdoor weather. Even winter in San Diego rarely prevents outdoor performances.',
    tips: [
      'Balboa Park\'s free Sunday organ concerts at 2pm have been running for over 100 years — a genuinely unique free music experience.',
      'North Park\'s bar strip on 30th Street has free local music most nights — The Casbah nearby is worth checking too.',
      'The Embarcadero Marina Park North hosts free concerts during summer — great harbor views included.',
      'San Diego Reader publishes a comprehensive free events calendar.',
      'Ocean Beach\'s Newport Avenue bars have free music on weekend nights — a very local, un-touristy vibe.',
    ],
    venues: [
      'Spreckels Organ Pavilion, Balboa Park — free Sundays at 2pm, year-round',
      'Embarcadero Marina Park — free outdoor concerts, summer',
      'The Casbah — local and touring acts, frequent affordable shows',
      'North Park\'s 30th Street bars — nightly local music, often free',
      'Ocean Beach venues (Newport Ave) — free shows on weekends',
      'Del Mar Fairgrounds — seasonal free outdoor stages',
    ],
    hoods: ['North Park', 'Ocean Beach', 'Pacific Beach', 'Hillcrest', 'Gaslamp Quarter', 'Normal Heights'],
  },

  'phoenix': {
    intro: 'Phoenix\'s free music scene thrives in the cooler months — fall through spring — when the desert climate is perfect for outdoor concerts. From the Roosevelt Row arts district to Tempe\'s Mill Avenue scene and Scottsdale\'s waterfront, the Valley of the Sun offers diverse free live music options.',
    scene: 'Phoenix\'s free music landscape is shaped by its climate: outdoor music happens primarily from October through April, when temperatures are ideal. First Friday Art Walk in the Roosevelt Row (RoRo) arts district brings thousands out for free gallery openings and live street music on the first Friday of each month. Tempe Town Lake hosts free outdoor concerts. The Musical Instrument Museum offers free public programming. Scottsdale Quarter and Old Town Scottsdale host outdoor performances. The bar scene in Tempe, close to ASU, is particularly active with affordable and free shows.',
    where: 'Roosevelt Row (RoRo) First Friday Art Walk is Phoenix\'s best free music event — street performances, gallery openings, and an electric atmosphere every first Friday, year-round (though summer draws smaller crowds). Tempe Town Lake\'s Tempe Beach Park hosts free outdoor concerts during the fall and spring seasons. Modified Arts in downtown Phoenix books free art and music events. Scottsdale\'s ArtWalk on Thursday evenings features live music in galleries and outdoor spaces.',
    seasons: 'Phoenix outdoor free music season runs October through April. The summer months (May–September) are too hot for comfortable outdoor events, though indoor shows continue at bars and venues. First Friday Art Walk happens year-round but is best October–April. Tempe\'s bar and club scene near ASU is most active during the school year.',
    tips: [
      'First Friday Art Walk in Roosevelt Row is the best free music event in Phoenix — go from October through April for the best experience.',
      'Tempe Town Lake\'s free outdoor concerts are excellent; check Tempe.gov for the events calendar.',
      'ASU Gammage has occasional free public programming; check their calendar.',
      'Tempe\'s Mill Avenue and nearby bars have live music nightly, especially during the school year.',
      'Scottsdale\'s Thursday ArtWalk (Old Town) often features live music outdoors — a nice evening activity.',
    ],
    venues: [
      'Roosevelt Row — First Friday Art Walk, monthly free street music',
      'Tempe Beach Park — free outdoor concerts, fall and spring',
      'Modified Arts — free art and music events, downtown Phoenix',
      'Crescent Ballroom — local and touring acts, occasional free shows',
      'Valley Bar — downtown Phoenix, local music, accessible pricing',
      'Scottsdale\'s Old Town — Thursday ArtWalk, outdoor music',
    ],
    hoods: ['Roosevelt Row', 'Downtown Phoenix', 'Tempe', 'Old Town Scottsdale', 'Midtown', 'Chandler'],
  },

  'st-louis': {
    intro: 'St. Louis offers an underrated free music scene rooted in its blues heritage and a thriving local music community. The Gateway City\'s Forest Park, the Loop, and Cherokee Street all deliver accessible live music, and the Missouri History Museum and other institutions round out a full calendar.',
    scene: 'St. Louis\'s free music scene draws on a blues and rock tradition that runs deep in the city\'s culture. Forest Park — one of America\'s largest urban parks — hosts free outdoor concerts throughout summer. The Delmar Loop on University City\'s border has bars and venues with nightly live music. The Folk & Roots Festival in Schlafly Bottleworks presents free music. Cherokee Street\'s eclectic bar scene features local bands with no cover. The Missouri History Museum and Art Museum present free public programming including music.',
    where: 'Forest Park\'s Art Hill and the Muny (Municipal Opera) area host free outdoor performances in summer. The Delmar Loop has the best concentration of live music bars with frequent free shows. The Soulard neighborhood — St. Louis\'s historic French Quarter — features live blues and R&B at bars with accessible covers and occasional free nights. Cherokee Street\'s hip independent scene books local acts in bars and gallery spaces. Laumeier Sculpture Park hosts free outdoor concerts in its beautiful grounds.',
    seasons: 'Summer (June–September) is peak outdoor free music season with Forest Park programming and the Muny\'s free bench seating. The Delmar Loop and Cherokee Street bars are active year-round. Soulard\'s bar scene peaks around Mardi Gras (February) with incredible free street music. Fall brings excellent outdoor weather for smaller events.',
    tips: [
      'The Muny in Forest Park offers free bench seating at every performance — arrive early to claim a spot before the shows start.',
      'Forest Park itself hosts free summer concerts at various locations; check stlouis-mo.gov/parks.',
      'Soulard\'s bars have live blues nightly — B.B.\'s Jazz, Blues & Soups is a longtime institution.',
      'Cherokee Street\'s First Friday events feature free outdoor music in an eclectic arts district setting.',
      'St. Louis Post-Dispatch events section covers free music listings.',
    ],
    venues: [
      'The Muny, Forest Park — free bench seating, summer opera and musicals',
      'Forest Park — free outdoor concerts, summer',
      'Laumeier Sculpture Park — free outdoor music events',
      'BB\'s Jazz, Blues & Soups — Soulard, live music nightly',
      'The Delmar Loop (University City) — bar strip, frequent free shows',
      'Cherokee Street venues — local music, art walks with live music',
    ],
    hoods: ['Soulard', 'Cherokee Street', 'Delmar Loop', 'The Grove', 'Tower Grove', 'Downtown'],
  },

  'baltimore': {
    intro: 'Baltimore\'s free music scene is gritty, authentic, and deeply tied to the city\'s working-class neighborhoods. From the Inner Harbor\'s summer stages to Charles Village\'s bars and Pigtown\'s dive clubs, Baltimore rewards music seekers who get off the tourist trail.',
    scene: 'Baltimore\'s free music landscape includes the Baltimore Symphony\'s free outdoor concerts, Inner Harbor summer programming, and a thriving bar scene in neighborhoods like Hampden, Fells Point, and Charles Village. Artscape — held annually in July — is the largest free arts festival in the country and features multiple music stages. WTMD radio station sponsors free concerts. The Creative Alliance in Patterson Park hosts free and low-cost events. Hampdenfest and other neighborhood festivals add to the free music calendar.',
    where: 'Artscape in July is the crown jewel of Baltimore free music — multiple stages across the Mount Royal Avenue corridor with major and emerging acts. The Inner Harbor amphitheater hosts summer concerts. Pier 6 Concert Pavilion\'s free outdoor lawn area offers views of ticketed shows. Fells Point\'s waterfront bars book live music nightly. Hampden\'s 36th Street ("The Avenue") has bars with free local bands. Patterson Park hosts free outdoor events in summer.',
    seasons: 'Summer is peak free music season with Artscape (July), Inner Harbor programming, and neighborhood festivals. Fells Point and Hampden bars are active year-round. Fall brings excellent weather for outdoor events. Winter\'s indoor bar scene keeps the music going on weekends.',
    tips: [
      'Artscape in July is enormous and completely free — arrive Saturday for the best crowds and headliners.',
      'Fells Point\'s Broadway Square and waterfront bars have live music on weekends, often no cover.',
      'Hampden\'s 36th Street bars (Rocket to Venus, The Ivy Bookshop area) have free local music regularly.',
      'WTMD radio (89.7 FM) hosts free outdoor concerts and promotes free events — check wtmd.org.',
      'Patterson Park\'s summer programming includes free concerts on the lawn.',
    ],
    venues: [
      'Artscape Festival venues (July) — multiple free stages across Mount Royal',
      'Inner Harbor Amphitheater — summer outdoor concerts',
      'Patterson Park — free summer programming',
      'Ottobar — local music venue, occasional free shows',
      'Fells Point Square — waterfront music and events',
      'Hampden\'s 36th Street bars — free local music, weekends',
    ],
    hoods: ['Fells Point', 'Hampden', 'Charles Village', 'Federal Hill', 'Station North', 'Pigtown'],
  },

  'pittsburgh': {
    intro: 'Pittsburgh\'s free music scene is anchored by Pittsburgh Parks Conservancy concerts, the Three Rivers Jazz Festival, and a neighborhood bar scene in Lawrenceville and South Side where local bands play nightly without a cover charge.',
    scene: 'Pittsburgh\'s free music culture draws from its working-class roots and passionate local music community. The Pittsburgh Cultural Trust presents free outdoor programming at Cultural District venues. Point State Park at the confluence of the three rivers hosts the Three Rivers Arts Festival with free music stages in June. Hartwood Acres Park hosts free summer concerts featuring national touring acts. Lawrenceville\'s Butler Street bar strip has become the city\'s hottest music neighborhood with local bands nightly. WYEP radio and local music organizations promote accessible concerts across the city.',
    where: 'Hartwood Acres Park hosts free summer amphitheater concerts on Friday and Saturday evenings from June through August — a Pittsburgh tradition. Point State Park and nearby spaces host Three Rivers Arts Festival stages in June. The Cultural District\'s outdoor spaces and Heinz Hall present free public programming. Lawrenceville\'s bars (Spirit, Thunderbird Café) book local and touring acts at low or no cover. South Side\'s East Carson Street has bars with live music most nights.',
    seasons: 'Summer is peak outdoor free music with Hartwood Acres and Three Rivers Arts Festival. Lawrenceville and South Side bars are active year-round. Fall brings excellent football-adjacent bar culture with background music. Winter concentrates shows at indoor venues in the Strip District and Lawrenceville.',
    tips: [
      'Hartwood Acres\' free summer amphitheater concerts are a Pittsburgh institution — check Allegheny County Parks for the season lineup.',
      'Three Rivers Arts Festival (June) has free outdoor music stages in addition to art — check traf.trustarts.org.',
      'Lawrenceville\'s Spirit venue has frequent free and affordable shows — check their calendar.',
      'WYEP (91.3 FM) is Pittsburgh\'s best resource for free music listings and sponsors events.',
      'South Side\'s East Carson Street bars have live music most nights; many are free before midnight.',
    ],
    venues: [
      'Hartwood Acres Amphitheater — free Friday/Saturday concerts, summer',
      'Point State Park — Three Rivers Arts Festival stages (June)',
      'Spirit — Lawrenceville, local and touring acts, frequent free shows',
      'Thunderbird Café — Lawrenceville, local music, low covers',
      'Rex Theater — South Side, occasional free events',
      'Cultural District outdoor spaces — free programming',
    ],
    hoods: ['Lawrenceville', 'South Side', 'Strip District', 'East Liberty', 'Squirrel Hill', 'Shadyside'],
  },

  'charlotte': {
    intro: 'Charlotte\'s rapidly growing music scene reflects the city\'s booming population, with free outdoor concerts at Romare Bearden Park, NoDa neighborhood shows, and Plaza Midwood bars delivering accessible live music to a city that\'s become one of the South\'s most vibrant cultural hubs.',
    scene: 'Charlotte\'s free music landscape is relatively new but growing fast. Romare Bearden Park in uptown Charlotte hosts free outdoor concerts year-round. The NoDa (North Davidson) neighborhood is the city\'s arts and music hub, with bars and venues booking local acts nightly at no cover or low charge. The Charlotte Center City Partners run free outdoor programming. The Blumenthal Performing Arts Center has free public events. Plaza Midwood\'s bar scene on Central Avenue has expanded the city\'s free music options significantly.',
    where: 'Romare Bearden Park hosts free concerts as part of Charlotte\'s Center City programming — a great uptown outdoor venue. NoDa\'s main strip on Davidson Street has live music at NoDa Brewing, The Evening Muse, and other venues most nights of the week. Plaza Midwood\'s Central Avenue bars book local bands with no cover on weeknights. Camp North End, a redeveloped industrial campus, hosts free music events and arts festivals. The Charlotte Motor Speedway area hosts outdoor music events.',
    seasons: 'Charlotte\'s mild climate supports outdoor free music from March through November. Spring and fall are ideal. NoDa and Plaza Midwood bar scenes are active year-round. Summer brings outdoor festival programming to Romare Bearden Park and other downtown spaces.',
    tips: [
      'NoDa\'s Evening Muse is Charlotte\'s most beloved small music venue — they book excellent local and touring acts affordably.',
      'NoDa Brewing Company books free live music regularly in their taproom and outdoor spaces.',
      'Romare Bearden Park\'s free concert series calendar is at charlottecentercity.org.',
      'Plaza Midwood\'s Central Avenue strip has bars with free music on weeknights — a local favorite.',
      'Camp North End hosts free community music events; follow them on social media for announcements.',
    ],
    venues: [
      'Romare Bearden Park — free outdoor concerts, center city',
      'The Evening Muse — NoDa, local music, affordable shows',
      'NoDa Brewing Company — free live music in taproom',
      'Camp North End — free arts and music events',
      'Central Avenue bars (Plaza Midwood) — local bands, often free',
      'Neighborhood Theatre — NoDa, occasional free events',
    ],
    hoods: ['NoDa (North Davidson)', 'Plaza Midwood', 'South End', 'Dilworth', 'Uptown', 'NODA Arts District'],
  },

  'raleigh': {
    intro: 'Raleigh\'s free music scene is boosted by a large university population and a city government that invests in public arts programming. From the North Carolina Museum of Art\'s outdoor amphitheater to Glenwood South bars and the city\'s park concert series, the Triangle delivers genuine free music.',
    scene: 'Raleigh\'s free music landscape benefits from three major universities (NC State, UNC-Chapel Hill, Duke) generating both artists and audiences. The North Carolina Museum of Art (NCMA) presents the Artscenter Series with free outdoor concerts on its stunning grounds. Downtown Raleigh\'s Glenwood South and Fayetteville Street bars book local acts nightly. Cary Koka Booth Amphitheatre has free community programming. The North Hills area and Seaboard Station neighborhood have venues with regular free music nights.',
    where: 'The North Carolina Museum of Art\'s outdoor amphitheater and grounds host free Movies on the Museum Lawn and occasional free concerts — a beautiful outdoor space west of the city. Glenwood South\'s bar strip in downtown Raleigh has live music at Pour House Music Hall, Slim\'s Downtown, and other venues most nights. Warehouse District arts spaces host free community events with music. The North Hills outdoor plaza hosts free summer concerts. Cary\'s Town Square has free outdoor programming.',
    seasons: 'Spring (April–June) and fall (September–October) are ideal for outdoor free music in Raleigh\'s mild Piedmont climate. The NCMA grounds programming runs spring through fall. Glenwood South and other bar districts are active year-round. Summer evenings bring outdoor concerts; winter drives the scene indoors to venues and breweries.',
    tips: [
      'NC Museum of Art\'s free outdoor programming is excellent — check ncartmuseum.org for the season calendar.',
      'Pour House Music Hall on Glenwood South has frequent free local music — check their calendar.',
      'Slim\'s Downtown books local and touring acts with affordable pricing and occasional free shows.',
      'Raleigh\'s First Friday gallery walk includes live music at various downtown venues.',
      'Triangle area music blog Indy Week covers free music listings across Raleigh, Durham, and Chapel Hill.',
    ],
    venues: [
      'NC Museum of Art Amphitheater — free outdoor programming, spring–fall',
      'Pour House Music Hall — Glenwood South, local music, frequent free nights',
      'Slim\'s Downtown — local and touring acts, affordable covers',
      'Lincoln Theatre — occasional free events',
      'North Hills Plaza — free summer outdoor concerts',
      'Warehouse District spaces — free community events with music',
    ],
    hoods: ['Glenwood South', 'Warehouse District', 'Five Points', 'Cameron Village', 'North Hills', 'Seaboard Station'],
  },

  'new-orleans': {
    intro: 'New Orleans is in a class of its own for free live music. The city\'s culture is inseparable from its music, and jazz, brass bands, zydeco, and blues pour out of bars, street corners, and second-line parades with no admission required. Frenchmen Street alone makes New Orleans the greatest free music city in America.',
    scene: 'New Orleans\'s free music ecosystem is extraordinary and unlike anywhere else in the world. Frenchmen Street in the Marigny neighborhood has half a dozen venues booking jazz, funk, and brass bands every night — most free, starting around 9pm. Bourbon Street\'s bars blast live music continuously. Second-line parades happen most Sundays from October through June, marching through neighborhoods with brass bands and community celebration at no cost. Jackson Square features buskers and street performers daily. The French Quarter Festival in April is the world\'s largest free music festival. Jazz Fest has free stages. Preservation Hall charges a modest cover but nearby bars are free.',
    where: 'Frenchmen Street in the Marigny is the heart of authentic New Orleans free music — three or four blocks with venues like The Spotted Cat, Maison, and d.b.a. all booking live jazz and funk nightly with no cover. Jackson Square in the French Quarter has street musicians daily. Tipitina\'s in Uptown has free Sunday afternoon shows. The Maple Leaf Bar in Uptown features free Tuesday evening shows. Second-line parade routes through various neighborhoods are announced weekly by the NOLA Social Aid and Pleasure Club Task Force.',
    seasons: 'New Orleans is a year-round music city. The season of free music never ends. Winter brings Mardi Gras (February) with incredible free street music and parades. Spring brings French Quarter Festival (April, completely free) and Jazz Fest (paid admission but free stages nearby). Summer is hot and humid but indoor venues on Frenchmen Street are always active. Fall\'s second-line season is spectacular.',
    tips: [
      'Frenchmen Street is the most important place for authentic New Orleans free music — arrive after 9pm on any weekend night.',
      'The Spotted Cat on Frenchmen Street has live jazz or swing every single night, never a cover.',
      'Second-line parades happen almost every Sunday from October through June — the NOLA Social Aid and Pleasure Club Task Force posts the schedule.',
      'French Quarter Festival in April is the world\'s largest free music festival — 40+ stages, 1,700 musicians, all free.',
      'Tip the musicians everywhere — this is how they make their living.',
    ],
    venues: [
      'The Spotted Cat Music Club — Frenchmen Street, jazz nightly, free',
      'Maison — Frenchmen Street, multiple stages, free',
      'd.b.a. — Frenchmen Street, jazz and funk, free most nights',
      'Maple Leaf Bar — Uptown, free Tuesday shows',
      'Tipitina\'s — Uptown, free Sunday afternoon shows (seasonal)',
      'Jackson Square — French Quarter, daily street performers and buskers',
    ],
    hoods: ['Frenchmen Street / Marigny', 'French Quarter', 'Uptown', 'Tremé', 'Mid-City', 'Bywater'],
  },
}
