import { Concert } from '@/types'

export const MOCK_CONCERTS: Concert[] = [
  // ── NYC ────────────────────────────────────────────────────────────────
  {
    id: '1',
    display_id: 'NYC-2026-000001',
    slug: 'mutual-benefit-naumburg-bandshell-apr28',
    artist_name: 'Mutual Benefit',
    venue: 'Naumburg Bandshell',
    date: '2026-04-28',
    time: '7:00 PM',
    neighborhood: 'Central Park',
    city: 'NYC',
    genre: 'Folk',
    price: 'Free',
    admission_type: 'Walk-up free',
    indoor_outdoor: 'Outdoor',
    image_url: null,
    is_verified: true,
    source_name: 'Naumburg Orchestral Concerts',
    source_id: 'naum-2026-001',
    source_url: 'https://www.naumburg.org',
    venue_id: null,
    series_id: null,
    is_cancelled: false,
    created_at: '2026-01-01',
  },
  {
    id: '2',
    display_id: 'NYC-2026-000002',
    slug: 'samara-joy-bryant-park-lawn-apr28',
    artist_name: 'Samara Joy',
    venue: 'Bryant Park Lawn',
    date: '2026-04-28',
    time: '6:30 PM',
    neighborhood: 'Midtown',
    city: 'NYC',
    genre: 'Jazz',
    price: 'Free',
    admission_type: 'Walk-up free',
    indoor_outdoor: 'Outdoor',
    image_url: null,
    is_verified: true,
    source_name: 'Bryant Park',
    source_id: 'bp-2026-042',
    source_url: 'https://bryantpark.org/programs',
    venue_id: null,
    series_id: null,
    is_cancelled: false,
    created_at: '2026-01-01',
  },
  {
    id: '3',
    display_id: 'NYC-2026-000003',
    slug: 'jeff-tweedy-summerstage-apr30',
    artist_name: 'Jeff Tweedy',
    venue: 'SummerStage',
    date: '2026-04-30',
    time: '7:00 PM',
    neighborhood: 'Upper East Side',
    city: 'NYC',
    genre: 'Indie Rock',
    price: 'Free',
    admission_type: 'Free RSVP',
    indoor_outdoor: 'Outdoor',
    image_url: null,
    is_verified: true,
    source_name: 'SummerStage',
    source_id: 'ss-2026-019',
    source_url: 'https://cityparksfoundation.org/summerstage',
    venue_id: null,
    series_id: null,
    is_cancelled: false,
    created_at: '2026-01-01',
  },
  {
    id: '4',
    display_id: 'NYC-2026-000004',
    slug: 'arooj-aftab-lincoln-center-out-of-doors-may01',
    artist_name: 'Arooj Aftab',
    venue: 'Lincoln Center Out of Doors',
    date: '2026-05-01',
    time: '7:30 PM',
    neighborhood: 'Upper West Side',
    city: 'NYC',
    genre: 'Neo-soul',
    price: 'Free',
    admission_type: 'Free RSVP',
    indoor_outdoor: 'Outdoor',
    image_url: null,
    is_verified: true,
    source_name: 'Lincoln Center',
    source_id: 'lc-2026-055',
    source_url: 'https://www.lincolncenter.org/series/out-of-doors',
    venue_id: null,
    series_id: null,
    is_cancelled: false,
    created_at: '2026-01-01',
  },
  {
    id: '5',
    display_id: 'NYC-2026-000005',
    slug: 'hermanos-gutierrez-prospect-park-bandshell-may02',
    artist_name: 'Hermanos Gutiérrez',
    venue: 'Prospect Park Bandshell',
    date: '2026-05-02',
    time: '7:00 PM',
    neighborhood: 'Prospect Heights',
    city: 'NYC',
    genre: 'Latin Folk',
    price: 'Free',
    admission_type: 'Free RSVP',
    indoor_outdoor: 'Outdoor',
    image_url: null,
    is_verified: true,
    source_name: 'Celebrate Brooklyn!',
    source_id: 'cb-2026-007',
    source_url: 'https://bricartsmedia.org/celebrate-brooklyn',
    venue_id: null,
    series_id: null,
    is_cancelled: false,
    created_at: '2026-01-01',
  },
  {
    id: '6',
    display_id: 'NYC-2026-000006',
    slug: 'cautious-clay-brooklyn-bridge-park-pier-1-may03',
    artist_name: 'Cautious Clay',
    venue: 'Brooklyn Bridge Park Pier 1',
    date: '2026-05-03',
    time: '6:00 PM',
    neighborhood: 'Brooklyn Heights',
    city: 'NYC',
    genre: 'R&B',
    price: 'Free',
    admission_type: 'Free RSVP',
    indoor_outdoor: 'Outdoor',
    image_url: null,
    is_verified: false,
    source_name: 'Brooklyn Bridge Park',
    source_id: 'bbp-2026-033',
    source_url: 'https://brooklynbridgepark.org/events',
    venue_id: null,
    series_id: null,
    is_cancelled: false,
    created_at: '2026-01-01',
  },
  {
    id: '7',
    display_id: 'NYC-2026-000007',
    slug: 'ezra-collective-fort-tryon-park-may09',
    artist_name: 'Ezra Collective',
    venue: 'Fort Tryon Park',
    date: '2026-05-09',
    time: '5:30 PM',
    neighborhood: 'Washington Heights',
    city: 'NYC',
    genre: 'Jazz',
    price: 'Free',
    admission_type: 'Free RSVP',
    indoor_outdoor: 'Outdoor',
    image_url: null,
    is_verified: true,
    source_name: 'Fort Tryon Park Trust',
    source_id: 'ftp-2026-011',
    source_url: 'https://forttryon.org',
    venue_id: null,
    series_id: null,
    is_cancelled: false,
    created_at: '2026-01-01',
  },
  {
    id: '8',
    display_id: 'NYC-2026-000008',
    slug: 'faye-webster-rockaway-beach-boardwalk-may10',
    artist_name: 'Faye Webster',
    venue: 'Rockaway Beach Boardwalk',
    date: '2026-05-10',
    time: '4:00 PM',
    neighborhood: 'Rockaway',
    city: 'NYC',
    genre: 'Indie Pop',
    price: 'Free',
    admission_type: 'Walk-up free',
    indoor_outdoor: 'Outdoor',
    image_url: null,
    is_verified: false,
    source_name: 'NYC Parks',
    source_id: 'nycparks-26-0812',
    source_url: 'https://www.nycgovparks.org/events',
    venue_id: null,
    series_id: null,
    is_cancelled: false,
    created_at: '2026-01-01',
  },
  {
    id: '9',
    display_id: 'NYC-2026-000009',
    slug: 'wednesday-mccarren-park-may14',
    artist_name: 'Wednesday',
    venue: 'McCarren Park',
    date: '2026-05-14',
    time: '7:00 PM',
    neighborhood: 'Williamsburg',
    city: 'NYC',
    genre: 'Alt-country',
    price: 'Free',
    admission_type: 'Walk-up free',
    indoor_outdoor: 'Outdoor',
    image_url: null,
    is_verified: false,
    source_name: 'NYC Parks',
    source_id: 'nycparks-26-0891',
    source_url: 'https://www.nycgovparks.org/events',
    venue_id: null,
    series_id: null,
    is_cancelled: false,
    created_at: '2026-01-01',
  },
  {
    id: '10',
    display_id: 'NYC-2026-000010',
    slug: 'mdou-moctar-east-river-park-amphitheater-may16',
    artist_name: 'Mdou Moctar',
    venue: 'East River Park Amphitheater',
    date: '2026-05-16',
    time: '6:00 PM',
    neighborhood: 'Lower East Side',
    city: 'NYC',
    genre: 'Psychedelic',
    price: 'Free',
    admission_type: 'Walk-up free',
    indoor_outdoor: 'Outdoor',
    image_url: null,
    is_verified: false,
    source_name: 'NYC Parks',
    source_id: 'nycparks-26-0922',
    source_url: 'https://www.nycgovparks.org/events',
    venue_id: null,
    series_id: null,
    is_cancelled: false,
    created_at: '2026-01-01',
  },
  // ── LA ─────────────────────────────────────────────────────────────────
  {
    id: '11',
    display_id: 'LAX-2026-000001',
    slug: 'gillian-welch-the-getty-center-apr28',
    artist_name: 'Gillian Welch',
    venue: 'The Getty Center',
    date: '2026-04-28',
    time: '6:00 PM',
    neighborhood: 'Brentwood',
    city: 'LA',
    genre: 'Folk',
    price: 'Free',
    admission_type: 'Free RSVP',
    indoor_outdoor: 'Outdoor',
    image_url: null,
    is_verified: true,
    source_name: 'The Getty',
    source_id: 'getty-2026-018',
    source_url: 'https://www.getty.edu/visit/events',
    venue_id: null,
    series_id: null,
    is_cancelled: false,
    created_at: '2026-01-01',
  },
  {
    id: '12',
    display_id: 'LAX-2026-000002',
    slug: 'thundercat-grand-performances-apr28',
    artist_name: 'Thundercat',
    venue: 'Grand Performances',
    date: '2026-04-28',
    time: '8:00 PM',
    neighborhood: 'DTLA',
    city: 'LA',
    genre: 'Jazz/Funk',
    price: 'Free',
    admission_type: 'Walk-up free',
    indoor_outdoor: 'Outdoor',
    image_url: null,
    is_verified: true,
    source_name: 'Grand Performances',
    source_id: 'gp-2026-004',
    source_url: 'https://grandperformances.org',
    venue_id: null,
    series_id: null,
    is_cancelled: false,
    created_at: '2026-01-01',
  },
  {
    id: '13',
    display_id: 'LAX-2026-000003',
    slug: 'bedouine-barnsdall-art-park-apr29',
    artist_name: 'Bedouine',
    venue: 'Barnsdall Art Park',
    date: '2026-04-29',
    time: '7:00 PM',
    neighborhood: 'Los Feliz',
    city: 'LA',
    genre: 'Folk',
    price: 'Free',
    admission_type: 'Walk-up free',
    indoor_outdoor: 'Outdoor',
    image_url: null,
    is_verified: true,
    source_name: 'LA Parks',
    source_id: 'laparks-26-0221',
    source_url: 'https://www.laparks.org',
    venue_id: null,
    series_id: null,
    is_cancelled: false,
    created_at: '2026-01-01',
  },
  {
    id: '14',
    display_id: 'LAX-2026-000004',
    slug: 'nick-hakim-lacma-jazz-may01',
    artist_name: 'Nick Hakim',
    venue: 'LACMA Jazz',
    date: '2026-05-01',
    time: '6:30 PM',
    neighborhood: 'Mid-Wilshire',
    city: 'LA',
    genre: 'Soul',
    price: 'Free',
    admission_type: 'Free RSVP',
    indoor_outdoor: 'Outdoor',
    image_url: null,
    is_verified: true,
    source_name: 'LACMA',
    source_id: 'lacma-2026-083',
    source_url: 'https://www.lacma.org/programs/free-jazz-sundays',
    venue_id: null,
    series_id: null,
    is_cancelled: false,
    created_at: '2026-01-01',
  },
  {
    id: '15',
    display_id: 'LAX-2026-000005',
    slug: 'cuco-santa-monica-pier-may02',
    artist_name: 'Cuco',
    venue: 'Santa Monica Pier',
    date: '2026-05-02',
    time: '7:30 PM',
    neighborhood: 'Santa Monica',
    city: 'LA',
    genre: 'Dream Pop',
    price: 'Free',
    admission_type: 'Walk-up free',
    indoor_outdoor: 'Outdoor',
    image_url: null,
    is_verified: false,
    source_name: 'Santa Monica Pier',
    source_id: 'smp-2026-015',
    source_url: 'https://santamonicapier.org/events',
    venue_id: null,
    series_id: null,
    is_cancelled: false,
    created_at: '2026-01-01',
  },
  {
    id: '16',
    display_id: 'LAX-2026-000006',
    slug: 'khruangbin-the-hammer-museum-may03',
    artist_name: 'Khruangbin',
    venue: 'The Hammer Museum',
    date: '2026-05-03',
    time: '5:00 PM',
    neighborhood: 'Westwood',
    city: 'LA',
    genre: 'Psychedelic',
    price: 'Free',
    admission_type: 'Free RSVP',
    indoor_outdoor: 'Outdoor',
    image_url: null,
    is_verified: true,
    source_name: 'The Hammer Museum',
    source_id: 'hammer-2026-029',
    source_url: 'https://hammer.ucla.edu/programs',
    venue_id: null,
    series_id: null,
    is_cancelled: false,
    created_at: '2026-01-01',
  },
  {
    id: '17',
    display_id: 'LAX-2026-000007',
    slug: 'illuminati-hotties-levitt-pavilion-may07',
    artist_name: 'illuminati hotties',
    venue: 'Levitt Pavilion',
    date: '2026-05-07',
    time: '7:00 PM',
    neighborhood: 'MacArthur Park',
    city: 'LA',
    genre: 'Indie Rock',
    price: 'Free',
    admission_type: 'Walk-up free',
    indoor_outdoor: 'Outdoor',
    image_url: null,
    is_verified: false,
    source_name: 'Levitt Foundation',
    source_id: 'levitt-2026-041',
    source_url: 'https://levittla.org',
    venue_id: null,
    series_id: null,
    is_cancelled: false,
    created_at: '2026-01-01',
  },
  {
    id: '18',
    display_id: 'LAX-2026-000008',
    slug: 'moonchild-grand-performances-may09',
    artist_name: 'Moonchild',
    venue: 'Grand Performances',
    date: '2026-05-09',
    time: '8:00 PM',
    neighborhood: 'DTLA',
    city: 'LA',
    genre: 'Neo-soul',
    price: 'Free',
    admission_type: 'Walk-up free',
    indoor_outdoor: 'Outdoor',
    image_url: null,
    is_verified: true,
    source_name: 'Grand Performances',
    source_id: 'gp-2026-017',
    source_url: 'https://grandperformances.org',
    venue_id: null,
    series_id: null,
    is_cancelled: false,
    created_at: '2026-01-01',
  },
  {
    id: '19',
    display_id: 'LAX-2026-000009',
    slug: 'valerie-june-the-getty-center-may14',
    artist_name: 'Valerie June',
    venue: 'The Getty Center',
    date: '2026-05-14',
    time: '6:00 PM',
    neighborhood: 'Brentwood',
    city: 'LA',
    genre: 'Folk',
    price: 'Free',
    admission_type: 'Free RSVP',
    indoor_outdoor: 'Outdoor',
    image_url: null,
    is_verified: true,
    source_name: 'The Getty',
    source_id: 'getty-2026-031',
    source_url: 'https://www.getty.edu/visit/events',
    venue_id: null,
    series_id: null,
    is_cancelled: false,
    created_at: '2026-01-01',
  },
  {
    id: '20',
    display_id: 'LAX-2026-000010',
    slug: 'sudan-archives-levitt-pavilion-may16',
    artist_name: 'Sudan Archives',
    venue: 'Levitt Pavilion',
    date: '2026-05-16',
    time: '7:30 PM',
    neighborhood: 'MacArthur Park',
    city: 'LA',
    genre: 'Electronic',
    price: 'Free',
    admission_type: 'Walk-up free',
    indoor_outdoor: 'Outdoor',
    image_url: null,
    is_verified: false,
    source_name: 'Levitt Foundation',
    source_id: 'levitt-2026-058',
    source_url: 'https://levittla.org',
    venue_id: null,
    series_id: null,
    is_cancelled: false,
    created_at: '2026-01-01',
  },
]
