#!/usr/bin/env python3
"""Check all unique source_urls for broken links (non-2xx or timeout)."""

import concurrent.futures
import urllib.request
import urllib.error
import ssl
import sys

URLS_WITH_COUNTS = [
    ("https://musicianscorner.com/calendar", 56),
    ("https://www.montereybayparent.com/free-summer-concerts-in-monterey-and-santa-cruz-counties/", 50),
    ("https://www.levittsiouxfalls.org/", 50),
    ("https://www.kennedy-center.org/whats-on/millennium-stage/", 49),
    ("https://parks.indy.gov/free-concert-series/", 43),
    ("https://cityparksfoundation.org/summerstage/", 40),
    ("https://www.visitlongbeach.com/blog/summer-concert-series/", 39),
    ("https://www.pacificsymphony.org/sotg", 38),
    ("https://www.balboapark.org/twilight-concerts", 33),
    ("https://enjoyorangecounty.com/summer-concert-series/", 30),
    ("https://levittdayton.org/concert-schedule/", 27),
    ("https://www.surfcityusa.com/events/live-music/", 26),
    ("https://www.scenepensacola.com/bands-on-the-beach-2026-schedule/", 25),
    ("https://downtownslo.com/events/concerts/lineup/", 24),
    ("https://bryantpark.org/programs/picnic-performances", 24),
    ("https://liverpoolchamber.com/chamber-info/chamber-committees/sub-committee-liverpool-is-the-place/", 24),
    ("https://familyfuninomaha.com/free-summer-concerts-omaha/", 24),
    ("https://www.milleroutdoortheatre.com/performance-list/", 23),
    ("https://lensic360.org/page/summer-scene", 22),
    ("https://www.wpb.org/Residents/Community-Events/Events/Clematis-by-Night", 21),
    ("https://revuewm.com/things-to-do/relax-at-rosa-returns-for-2026", 21),
    ("https://www.alleghenycounty.us/Parks-and-Events/Special-Events/Summer-Concerts-Series", 20),
    ("https://summerofthearts.org/sota-events/friday-night-concert-series/", 19),
    ("https://www.grantparkmusicfestival.com", 19),
    ("https://www.tingpavilion.com/events-tickets/fridaysafter5", 19),
    ("https://www.minneapolis.org/summer-dont-miss-list/events/concerts/", 19),
    ("https://lexfun4kids.com/summer-music-events/", 18),
    ("https://www.ocparks.com/news/oc-parks-presents-2026-summer-concert-series-and-sunset-cinema-film-series", 18),
    ("https://www.nightfallchattanooga.com/2026-featured-bands", 18),
    ("https://redondopier.com/events/", 17),
    ("https://waterfire.org/events/", 17),
    ("https://coronadoconcert.com/coronado-concert-schedule/", 17),
    ("https://www.knoxvilletn.gov/government/city_departments_offices/special_events/concerts_on_the_square", 17),
    ("https://overtonparkshell.org/freeconcertseries", 17),
    ("https://www.torranceca.gov/services/cultural-services-arts-and-classes/torrance-summer-nights", 16),
    ("https://pepperplacemarket.com/", 16),
    ("https://www.danapoint.org/departments/community-services-recreation/events-calendar", 16),
    ("https://www.lacma.org/programs/music", 15),
    ("https://southlandjamboree.org/schedule/", 15),
    ("https://mommypoppins.com/philadelphia-kids/free-activities/free-philly-summer-concerts-and-outdoor-music-festivals-for", 15),
    ("https://travelmakesmehappy.com/18-free-activities-and-live-music-near-orlando/", 15),
    ("https://www.minneapolis.org/calendar/seasonal/summer-events/", 15),
    ("https://tipitinas.com/calendar/", 15),
    ("https://www.a2sf.org/calendar/", 15),
    ("https://www.jasperwinery.com/summer-concert-series", 14),
    ("https://www.ampconcerts.org/", 14),
    ("https://www.experiencecolumbus.com/blog/post/columbus-summer-events-preview/", 14),
    ("https://www.lock3live.com/midday-on-main", 14),
    ("https://www.tri-c.edu/jazzfest/outdoor-lineup.html", 14),
    ("https://myfountainsquare.com/series/jazz-26/", 14),
    ("https://levittdenver.org", 14),
    ("https://www.atlantaonthecheap.com/peachtree-corners-outdoor-summer-concert-series/", 13),
    ("https://www.portland.gov/parks/arts-culture/summer-free-all/cultural-events", 13),
    ("https://www.nws.usace.army.mil/Missions/Civil-Works/Locks-and-Dams/Chittenden-Locks/", 13),
    ("https://www.beverlyhills.org/1313/Concerts-on-Canon---June-through-August", 13),
    ("https://www.musep.org", 13),
    ("https://www.lincolncenter.org/series/summer-for-the-city", 13),
    ("https://localspins.com/free-outdoor-community-concerts-2026/", 13),
    ("https://www.downtownelcajon.com/events/music-on-main/entertainment-schedule", 13),
    ("https://www.manhattanbeach.gov/?navid=1643", 13),
    ("https://thelongcenter.org/thedropin/", 13),
    ("https://alpenglownights.com/", 12),
    ("https://cincylagerhouse.com/rockin-the-roebling/", 12),
    ("https://www.canalside.com/events/", 12),
    ("https://toledo.oh.gov/summer/ottawa-park-concert-series", 12),
    ("https://mobigmusic.org/concerts", 12),
    ("https://www.visitjacksonville.com/events/riverside-arts-market/", 12),
    ("https://www.northcoastharbor.org/symphony-at-sunset", 12),
    ("https://belleislestateparkfriends.org/music-by-the-river/", 12),
    ("https://www.pennypack.org/", 12),
    ("https://www.visitvirginiabeach.com/events/", 11),
    ("https://valleycultural.org/concerts-events/", 11),
    ("https://www.cincinnati-oh.gov/cincyparks/visit-a-park/parks-events-calendar/music-at-the-esplanade/", 11),
    ("https://www.sterngrove.org/", 11),
    ("https://www.bandsinthesandvb.com/lineup/", 11),
    ("https://nysmusic.com/2026/03/11/2026-rochester-international-jazz-festival-announces-lineup/", 10),
    ("https://college.berklee.edu/events/summer/boston-public-library", 10),
    ("https://raleighnc.gov/parks-and-recreation/news/2026-summer-concert-series", 10),
    ("https://www.parks.fortlauderdale.gov/special-events/special-events/starlight-musicals", 10),
    ("https://cityparkjazz.org", 10),
    ("https://www.blueashevents.com/parks/fridayconcerts.php", 10),
    ("https://www.kentwood.us/events_detail_T53_R64.php", 10),
    ("https://www.blueashparksandrec.com/parks/tuesdayconcerts.php", 10),
    ("https://www.hopkinsartscenter.com/263/The-Sunset-Series-Outdoor-Concerts", 10),
    ("https://uticasquare.com/events/summers-fifth-night/", 10),
    ("https://hbconcertband.org/SummerSeries/", 10),
    ("https://tulsaworld.com/life-entertainment/local/music/article_5a5e628c-e8f4-4ece-a788-1d53a79064f6.html", 10),
    ("https://www.atlantaonthecheap.com/alpharetta-summer-concerts/", 10),
    ("https://www.rrpark.org/", 10),
    ("https://anchoragedowntown.org/adp-events/live-after-five-summer-concert-series/", 10),
    ("https://www.huntsvilleal.gov/environment/parks-recreation/activities-services/concerts-in-the-park/", 10),
    ("https://bricartsmedia.org/celebrate-brooklyn/", 10),
    ("https://rochester.kidsoutandabout.com/content/2026-rochester-lilac-festival", 10),
    ("https://hbconcertband.org/summerseries/", 10),
    ("https://www.missouribotanicalgarden.org/events-classes/signature-events/whitaker-music-festival", 10),
    ("https://www.glendaleca.gov/government/departments/community-services-parks/special-events", 9),
    ("https://www.carlsbadca.gov/departments/cultural-arts/performing-arts/tgif-concerts-in-the-parks", 9),
    ("https://www.chicago.gov/city/en/depts/dca/supp_info/millennium_park9.html", 9),
    ("https://urbanmilwaukee.com/pressrelease/washington-park-wednesdays-announces-2026-summer-concerts/", 9),
    ("https://events.visitsyracuse.com/events/category/live-music/", 9),
    ("https://bohemianlivemusic.org/outdoor-events/thursday-night-live/", 9),
    ("https://www.santamonica.com/events-calendar/", 9),
    ("https://vegasexperience.com/dtr/", 9),
    ("https://www.cityofsanteeca.gov/city-special-events/santee-summer-concerts", 9),
    ("https://www.portland5.com/events/music-main", 9),
    ("https://www.bandsonthebricks.com", 9),
    ("https://www.levittpavilionla.org/events", 9),
    ("https://santaclarita.gov/arts-and-culture/events/concerts-in-the-park/", 9),
    ("https://www.overtonparkshell.com", 9),
    ("https://civiccenterpark.org/events/concerts/", 9),
    ("https://www.crpd.org", 9),
    ("https://www.flagstaff.az.gov/5183/Concerts-in-the-Park", 9),
    ("https://playavista.com/events/", 9),
    ("https://www.cityoflakewood.us/", 9),
    ("https://www.inlander.com/music/checking-out-some-of-the-free-summer-concert-series-in-the-inland-northwest-28339705", 8),
    ("https://www.burlingtoncityarts.org/festivals-and-performance-series", 8),
    ("https://volunteerparktrust.org", 8),
    ("https://www.romanticasheville.com/five.htm", 8),
    ("https://artown.org/", 8),
    ("https://whitestown.in.gov/community/parks-and-recreation/events/concert-series/", 8),
    ("https://www.hartfordjazz.org/", 8),
    ("https://www.raisingarizonakids.com/events/westgate-wednesdays-2/", 8),
    ("https://www.soniclunch.com/", 8),
    ("https://excellenceconcerts.org/", 8),
    ("https://www.costamesaca.gov/government/departments-and-divisions/parks-and-community-services/events", 8),
    ("https://traf.trustarts.org/", 8),
    ("https://liveatthelakefront.com/", 8),
    ("https://www.chattanoogafun.com/events/", 8),
    ("https://www.culvercity.org/Events", 8),
    ("https://www.visitsacramento.com/blog/stories/post/sacramento-concerts-in-the-park-lineup/", 8),
    ("https://downtownseattle.org/events/downtown-summer-sounds/", 8),
    ("https://www.andoverks.com/", 8),
    ("https://cityofmissionviejo.org/events", 8),
    ("https://www.san-clemente.org/Home/Components/Calendar/Event/", 8),
    ("https://elizabethparkct.org/concerts-copy/", 8),
    ("https://www.danedances.org/", 8),
    ("https://www.fox6now.com/news/2026-chill-hill-schedule-21st-season-set-kick-off-june-9", 8),
    ("https://landmarksorchestra.org", 7),
    ("https://www.kogercenterforthearts.com/outreach/free-events/", 7),
    ("https://cityofirvine.org/community-library-services-department/summer-city", 7),
    ("https://www.southcarolinaexplorer.com/finlay-fridays-finlay-park-concerts/", 7),
    ("https://www.helloburlingtonvt.com/blog/post/outdoor-music-events-whats-happening-this-summer-in-burlington/", 7),
    ("https://www.cabq.gov/artsculture/historic-old-town/summertime-in-old-town", 7),
    ("https://valleycultural.org/concerts-events/noho-summer-nights/", 7),
    ("https://www.lagunabeachcity.net/government/departments/cultural-arts/performances/sunset-serenades", 7),
    ("https://folkheritage.org/asheville-events/shindig-on-the-green/", 7),
    ("https://www.firstandmaintowncenter.com/", 7),
    ("https://biia.org/summer-concert-series/", 7),
    ("https://tucson.com/life-entertainment/local/music/article_14b1c81a-f4d6-467a-a16a-17d30d45a696.html", 7),
    ("https://artown.org/Rancho/", 7),
    ("https://www.conservancyonline.com/events/musicianscornerfall", 7),
    ("https://www.gssepiscopal.org/jazz-in-the-garden", 7),
    ("https://portlandmaine.gov", 7),
    ("https://discoverkalispell.com/events/picnic-in-the-park-downtown/", 7),
    ("https://www.chestnuthill.org/pastorius_park_summer_concerts.php", 7),
    ("https://downtownboise.org/events/alive-after-five", 7),
    ("https://waterlandblog.com/save-the-dates-six-bands-set-for-2026-des-moines-summer-concert-series-on-wednesday-nights-from-july-15-aug-19/", 6),
    ("https://www.cityofbrea.gov/Calendar.aspx", 6),
    ("https://www.carenwestpr.com/atlanta-free-arts-festivals-spring-summer-guide/", 6),
    ("https://communitynewspapers.com/coral-gables-news/community-arts-program-cap-2026-summer-concert-series/", 6),
    ("https://www.ci.camarillo.ca.us", 6),
    ("https://www.starlightconcerts.org/", 6),
    ("https://www.morrisoncenter.com/events/neighborhood-concert-series", 6),
    ("https://thesquarepdx.org", 6),
    ("https://www.tulsakids.com/family-friendly-summer-concerts-in-tulsa/", 6),
    ("https://source.colostate.edu/lagoon-concert-series-2026-lineup-features-six-performances/", 6),
    ("https://www.arcadiaca.gov/recreation/parks-facilities/events", 6),
    ("https://www.lapalmaca.gov/220/Concerts-in-the-Park", 6),
    ("https://beaches.lacounty.gov/concerts/", 6),
    ("https://www.downtownsac.org/downtown-sac-experiences/concerts-in-the-park/", 6),
    ("https://www.rsrpd.org", 6),
    ("https://onelongfellowsquare.com/", 6),
    ("https://columbuscommons.org/events-hub/entertainment/", 6),
    ("https://www.anchorageconcerts.org/community/summer-concert-series/", 6),
    ("https://www.boston.gov/departments/parks-and-recreation/golf-course-concert-series", 6),
    ("https://naumburgconcerts.org/upcoming", 6),
    ("https://wpbparks.com/meyer-amphitheatre/", 6),
    ("https://tallahasseearts.org/levittamp/", 6),
    ("https://saltlakearts.org/programs/mondays-in-the-park", 6),
    ("https://www.fayetteville-ar.gov/515/Gulley-Park-Summer-Concert-Series", 6),
    ("https://esplanade.org/events/", 6),
    ("https://www.matsusentinel.com/where-to-catch-mostly-free-live-music-in-mat-su-this-summer/", 6),
    ("https://www.klydewarrenpark.org/events-programming", 6),
    ("https://www.concertofcolors.com/", 6),
    ("https://downtownbozeman.org/event/music-on-main-2026", 6),
    ("https://andersonparks.com/special-events/", 6),
    ("https://railroadpark.org", 6),
    ("https://indyarts.org/event/2026-levitt-vibe-indianapolis-music-series-may-concert/", 6),
    ("https://www.cityofmadison.com/news/2026-05-04/concerts-on-the-rooftop-returns-to-monona-terrace", 6),
    ("https://wcoconcerts.org/concerts-tickets/concerts-on-the-square", 6),
    ("https://thegallivancenter.com/events/", 6),
    ("https://www.choosechicago.com", 6),
    ("https://kansascityfwc26.com/fifa-fan-festival/", 6),
    ("https://www.visitlagunabeach.com/blog/sunset-serenades-in-laguna-beach/", 5),
    ("https://www.alisoviejo.org", 5),
    ("https://www.nbcdfw.com/news/local/dallas-symphony-announces-free-summer-concert-series/4013602/", 5),
    ("https://www.littlerock.com/events/annual-festivals-events/4th-of-july/", 5),
    ("https://www.samlarc.org/events", 5),
    ("https://www.lpm.org/waterfront-wednesday", 5),
    ("https://bixbyknollsinfo.com/concerts", 5),
    ("https://www.cityofalhambra.org/CivicAlerts.aspx?AID=289", 5),
    ("https://donapa.com/event/friday-nights-in-the-park-road-eleven-marshall-law/", 5),
    ("https://www.clarkcountynv.gov/government/departments/parks___recreation/events/jazz-in-the-park", 5),
    ("https://thecentreescondido.com/blog/live-at-the-centre-concert-series-2026/", 5),
    ("https://www.wyep.org/wyep-programming/2026-05-01/summer-music-festival-michgander-ratboys", 5),
    ("https://www.cityoflagunaniguel.org/calendar.aspx", 5),
    ("https://www.yorbalindaca.gov/404/Upcoming-Family-Fun-Special-Events", 5),
    ("https://www.getty.edu/whats-on/off-the-405/", 5),
    ("https://www.kiwanisoforange.org/concerts-in-the-park", 5),
    ("https://www.marietta.com/glover-park-concert-series", 5),
    ("https://miamionthecheap.com/free-events-at-north-beach-bandshell/", 5),
    ("https://www.colerain.org/246/Free-Sizzling-Summer-Entertainment-Serie", 5),
    ("https://www.nyphil.org/concerts-tickets/explore/parks/", 5),
    ("https://pattersonpark.com/concerts", 5),
    ("https://www.dallassymphony.org/community-education/in-the-community/symphony-in-the-city/", 5),
    ("https://www.visitsavannah.com/events/", 5),
    ("https://www.visitspokane.com/events/music-in-the-park/", 5),
    ("https://www.naplesislands.org/calendar", 4),
    ("https://www.buffalorising.com/2026/03/new-outdoor-concert-series-summer-of-jazz-series/", 4),
    ("https://news.mecknc.gov/news/new-sound-same-fun-meck-sounds-music-series-announced-2026", 4),
    ("https://www.cityofwestsacramento.org/government/departments/parks-recreation/westsacrhythmontheriver", 4),
    ("https://www.choosechicago.com/articles/festivals-special-events/chicago-jazz-festival/", 4),
    ("https://315thursdays.com/", 4),
    ("https://visitsouthernarizona.com/music-in-the-courtyard/", 4),
    ("https://pecanstreetfestival.org", 4),
    ("https://esplanade.org/groundbeat/", 4),
    ("https://www.cincinnati-oh.gov/cincyparks/visit-a-park/parks-events-calendar/gettin-to-the-point/", 4),
    ("https://myfountainsquare.com/series/2026-salsa-on-the-square-brought-to-you-by-pg/", 4),
    ("https://www.nashville.gov/departments/parks/cultural-arts/music", 4),
    ("https://www.eugene-or.gov/5103/Art-in-the-Parks", 4),
    ("https://sbparksandrec.santabarbaraca.gov/activities/community-events/concerts-park", 4),
    ("https://bohemianlivemusic.org/outdoor-events/global-sounds/", 4),
    ("https://playhousevillage.org/summer-concerts-in-the-village/", 4),
    ("https://iroquoisamphitheater.com/event-calendar/", 4),
    ("https://www.syracusejazzfest.com/schedule", 4),
    ("https://bradleyfair.com/events/", 4),
    ("https://www.familyfuntwincities.com/summer-music-twin-cities/", 4),
    ("https://www.atlantaonthecheap.com/city-green-live-concerts/", 4),
    ("https://gosouthcharleston.com/things-to-do/events/concerts-in-charleston-sc.html", 4),
    ("https://www.fox5vegas.com/2026/05/04/free-summer-concert-series-continues-lake-las-vegas/", 4),
    ("https://www.pacificsymphony.org/communityconcerts", 4),
    ("https://www.calleocho.com/event/viernes-culturales/", 4),
    ("https://www.delmarfoundation.org/programs/twilight/", 4),
    ("https://wearehuntsville.com/summer-sunset-concert-series-at-ditto-landing/", 4),
    ("https://www.hudsonyardsnewyork.com/backyard", 4),
    ("https://www.choosechicago.com/articles/chicago-music/chicago-blues-festival/", 4),
    ("https://belvederesquare.com/whats-up-at-the-square/summer-sounds/", 4),
    ("https://waterfrontbluesfest.com", 4),
    ("https://www.skirball.org/sunsetconcerts", 4),
    ("https://metroparkstoledo.com/musicingreenspaces", 4),
    ("https://www.gatewayfestivalorchestra.org/calendar-events/", 4),
    ("https://www.wtmd.org/radio/first-thursday-concerts-in-the-park/", 4),
    ("https://www.conservancyforcvnp.org/experience/rhythm-on-the-river/", 4),
    ("https://levittdayton.org/", 3),
    ("https://roughdraftatlanta.com/2026/04/25/atlanta-jazz-festival-announces-free-concert-series-at-local-parks-this-may/", 3),
    ("https://www.elsegundorecparks.gov/about-us/recparks-advanced-components/calendar-month-view", 3),
    ("https://www.bullockmuseum.org", 3),
    ("https://jacksonvillejazzfest.com/2026-schedule/", 3),
    ("https://www.reno.gov/Home/Components/Calendar/Event/31493/", 3),
    ("https://southlandjamboree.org/", 3),
    ("https://ncfolkfestival.com/", 3),
    ("https://ctvisit.com/articles/outdoor-summer-concert-series", 3),
    ("https://www.nixonlibrary.gov/sunday-concert-series", 3),
    ("https://www.arkansasfolklifefestival.org/", 3),
    ("https://www.kcsymphony.org/concerts-tickets/neighborhood-concerts/", 3),
    ("https://canalconvergence.com/", 3),
    ("https://stepoutbuffalo.com/guide-to-concerts-this-month-beyond-in-buffalo-wny/", 3),
    ("https://redriverculturaldistrict.org", 3),
    ("https://www.newportbeachca.gov/government/departments/library-services/cultural-arts/concerts-on-the-green", 3),
    ("https://www.richmondfolkfestival.org/", 3),
    ("https://www.thelongcenter.org/drop-in", 3),
    ("https://www.neworleans.com/events/", 3),
    ("https://gosouthsavannah.com/things-to-do/events/concerts-in-savannah-ga.html", 3),
    ("https://www.playingwithfireomaha.net/schedule", 3),
    ("https://www.tulsakids.com/family-friendly-festivals-in-the-tulsa-area/", 3),
    ("https://www.renoriverfestival.com/", 3),
    ("https://www.dacamera.com/free-events/", 3),
    ("https://renopublicmarket.com/", 3),
    ("https://www.longbeach.gov/lgb/", 3),
    ("https://wearehuntsville.com/concerts-on-the-dock-2/", 3),
    ("https://santafe.com/embrace-ancestrality-at-santa-fes-indigenousways-festival/", 3),
    ("https://www.archpark.org/events/blues-at-the-arch", 3),
    ("https://alabamasymphony.org/events/symphony-in-the-summer-railroad-park/", 3),
    ("https://www.universitycity.org/summerseries/", 3),
    ("https://www.northeastartskc.org/summer-concert", 3),
    ("https://www.parkstacoma.gov/", 3),
    ("https://www.ylcwats.com/", 3),
    ("https://piccolospoleto.com/festival-traditions/", 3),
    ("https://www.liveafterfive.com", 3),
    ("https://holycitysinner.com/entertainment/north-charleston-pops-announces-2026-jazz-in-the-park-series/", 3),
    ("https://capitolhillblockparty.com", 3),
    ("https://www.postandcourier.com/charleston_scene/music/charleston-concerts-may-2026/article_1ea0d082-f591-47b6-be12-c0f25cdf965d.html", 2),
    ("https://lbpeninsula.org/summer-concert-series/", 2),
    ("https://o-pa.org/learn-engage/music-at-miller-park/", 2),
    ("https://explorewhitefish.com/events", 2),
    ("https://bohemianlivemusic.org/outdoor-events/", 2),
    ("https://www.vromansbookstore.com", 2),
    ("https://tucsonpops.org/concerts", 2),
    ("https://www.artscape.org/", 2),
    ("https://southparkafter5.com/", 2),
    ("https://www.hollywoodartsparkexperience.com/", 2),
    ("https://hpblast.org/", 2),
    ("https://thatssotampa.com/top-tampa-weekend-events/", 2),
    ("https://flfinfest.com/jacksonville/home", 2),
    ("https://www.artsinthepark.org/", 2),
    ("https://www.charlotteonthecheap.com/charlotte-summer-concert-series/", 2),
    ("https://www.austintexas.org/blues-on-the-green", 2),
    ("https://charlestonconcertband.org/concerts", 2),
    ("https://www.curtishixonpark.com", 2),
    ("https://www.dcr.virginia.gov/state-parks/pocahontas-premieres", 2),
    ("https://stepoutbuffalo.com/big-fat-guide-to-summer-concerts-in-buffalo-wny/", 2),
    ("https://westgateaz.com/events/", 2),
    ("https://cathedralparkjazz.com", 2),
    ("https://xpn.org/free-at-noon", 2),
    ("https://www.metrophiladelphia.com/stories/best-philadelphia-area-music-festivals-summer-2026,138546", 2),
    ("https://highmarkmann.org/events", 2),
    ("https://college.berklee.edu/events/summer", 2),
    ("https://www.hermosabeach.gov/our-government/city-departments/community-resources-parks-recreation/hermosa-beach-concert-series", 2),
    ("https://www.bluesonthegreen.com", 2),
    ("https://northcity.com/", 2),
    ("https://alleghenyrivertrailpark.org/summer-concert-series/", 2),
    ("https://spectrumnews1.com/oh/cleveland/news/2026/05/05/cincinnati-parks-summer-concerts-2026", 2),
    ("https://www.greensboro-nc.gov/departments/parks-recreation/arts-cultural-programs/greensboro-cultural-center", 2),
    ("https://www.lenexa.com/Events-Activities/Arts-Music/Outdoor-Concert-Series", 2),
    ("https://www.sitkamusicfestival.org/events/55th-summer-music-festival", 2),
    ("https://www.toledo.oh.gov/", 1),
    ("https://www.grandperformances.org/events/ethiocali", 1),
    ("https://www.grandperformances.org/events/culture-clash", 1),
    ("https://www.nycgovparks.org/events/2026/06/10/ny-phil-harmonic-central-park", 1),
    ("https://maymont.org/calendar/skc/", 1),
    ("https://www.grandperformances.org/events/cola-2026-night-two", 1),
    ("https://www.grandperformances.org/events/la-county-fair-1", 1),
    ("https://www.goprovidence.com/blog/stories/post/mark-your-calendar-for-providences-cant-miss-events/", 1),
    ("https://www.grandperformances.org/events/the-art-of-crossfade-lecture-and-workshop", 1),
    ("https://www.grandperformances.org/events/cola-2026-night-one", 1),
]

CTX = ssl.create_default_context()
CTX.check_hostname = False
CTX.verify_mode = ssl.CERT_NONE

HEADERS = {"User-Agent": "Mozilla/5.0 (compatible; freelivemusic-checker/1.0)"}

def check(url_count):
    url, count = url_count
    try:
        req = urllib.request.Request(url, headers=HEADERS)
        with urllib.request.urlopen(req, timeout=8, context=CTX) as resp:
            return (url, count, resp.status, "OK")
    except urllib.error.HTTPError as e:
        return (url, count, e.code, str(e.reason))
    except Exception as e:
        return (url, count, 0, str(e)[:60])

print(f"Checking {len(URLS_WITH_COUNTS)} URLs...\n", flush=True)

broken = []
with concurrent.futures.ThreadPoolExecutor(max_workers=40) as ex:
    results = list(ex.map(check, URLS_WITH_COUNTS))

for url, count, status, reason in sorted(results, key=lambda x: -x[1]):
    if status not in (200, 301, 302, 303, 307, 308):
        broken.append((url, count, status, reason))

print(f"{'STATUS':>6}  {'CONCERTS':>8}  URL")
print("-" * 80)
for url, count, status, reason in sorted(broken, key=lambda x: -x[1]):
    print(f"{status:>6}  {count:>8}  {url}")
    print(f"         {'':>8}  ({reason})")

print(f"\n{len(broken)} broken URLs found out of {len(URLS_WITH_COUNTS)} checked.")
